Repository prj154654168/Sooum-BE, pull requests merged in 2024-09, with the labels that each got.

#33 Feat security 설정
  build.gradle
  src/main/java/com/sooum/core/domain/member/controller/MemberAuthController.java
  src/main/java/com/sooum/core/domain/member/dto/AuthDTO.java
  src/main/java/com/sooum/core/domain/member/entity/Blacklist.java
  src/main/java/com/sooum/core/domain/member/entity/RefreshToken.java
  src/main/java/com/sooum/core/domain/member/exception/DuplicateSignUpException.java
  src/main/java/com/sooum/core/domain/member/exception/MemberNotFoundException.java
  src/main/java/com/sooum/core/domain/member/exception/PolicyNotAllowException.java
  src/main/java/com/sooum/core/domain/member/mapper/MemberMapper.java
  src/main/java/com/sooum/core/domain/member/mapper/PolicyMapper.java
  src/main/java/com/sooum/core/domain/member/repository/BlacklistRepository.java
  src/main/java/com/sooum/core/domain/member/repository/MemberRepository.java
  src/main/java/com/sooum/core/domain/member/repository/PolicyRepository.java
  src/main/java/com/sooum/core/domain/member/repository/RefreshTokenRepository.java
  src/main/java/com/sooum/core/domain/member/service/MemberGetService.java
  src/main/java/com/sooum/core/domain/member/service/MemberSaveService.java
  src/main/java/com/sooum/core/domain/member/service/MemberService.java
  src/main/java/com/sooum/core/domain/member/service/PolicySaveService.java
  src/main/java/com/sooum/core/domain/member/service/RefreshTokenSaveService.java
  src/main/java/com/sooum/core/domain/member/usecase/MemberUseCase.java
  src/main/java/com/sooum/core/global/auth/annotation/CurrentUser.java
  src/main/java/com/sooum/core/global/auth/interceptor/JwtBlacklistInterceptor.java
  src/main/java/com/sooum/core/global/auth/interceptor/exception/JwtBlacklistException.java
  src/main/java/com/sooum/core/global/auth/resolver/CurrentUserArgumentResolver.java
  src/main/java/com/sooum/core/global/config/jwt/JwtAuthenticationFilter.java
  src/main/java/com/sooum/core/global/config/jwt/JwtProperties.java
  src/main/java/com/sooum/core/global/config/jwt/TokenProvider.java
  src/main/java/com/sooum/core/global/config/mvc/WebMvcConfig.java
  src/main/java/com/sooum/core/global/config/security/SecurityConfig.java
  src/main/java/com/sooum/core/global/responseform/ResponseEntityModel.java
  src/main/resources/application.yml
Labels: 경규, feature

#34 Latest feed api
  .gitignore
  build.gradle
  src/main/java/com/sooum/core/CoreApplication.java
  src/main/java/com/sooum/core/domain/block/repository/BlockRepository.java
  src/main/java/com/sooum/core/domain/block/service/BlockMemberService.java
  src/main/java/com/sooum/core/domain/card/controller/LatestFeedController.java
  src/main/java/com/sooum/core/domain/card/dto/FeedCardDto.java
  src/main/java/com/sooum/core/domain/card/dto/LatestFeedCardDto.java
  src/main/java/com/sooum/core/domain/card/entity/CommentCard.java
  src/main/java/com/sooum/core/domain/card/entity/FeedCard.java
  src/main/java/com/sooum/core/domain/card/entity/FeedLike.java
  src/main/java/com/sooum/core/domain/card/repository/CommentCardRepository.java
  src/main/java/com/sooum/core/domain/card/repository/FeedCardRepository.java
  src/main/java/com/sooum/core/domain/card/repository/FeedLikeRepository.java
  src/main/java/com/sooum/core/domain/card/service/CommentCardService.java
  src/main/java/com/sooum/core/domain/card/service/FeedCardService.java
  src/main/java/com/sooum/core/domain/card/service/FeedLikeService.java
  src/main/java/com/sooum/core/domain/card/service/FeedService.java
  src/main/java/com/sooum/core/domain/card/service/LatestFeedService.java
  src/main/java/com/sooum/core/domain/member/repository/PolicyTermRepository.java
  src/main/java/com/sooum/core/domain/member/service/PolicySaveService.java
  src/main/java/com/sooum/core/domain/member/usecase/MemberUseCase.java
  src/main/java/com/sooum/core/global/config/async/AsyncConfig.java
  src/main/java/com/sooum/core/global/config/security/SecurityConfig.java
  src/main/java/com/sooum/core/global/responseform/ResponseEntityModel.java
  src/main/java/com/sooum/core/global/responseform/ResponseStatus.java
  src/main/java/com/sooum/core/global/util/DistanceUtils.java
  src/main/java/com/sooum/core/global/util/NextPageLinkGenerator.java
  src/main/resources/application.yml
Labels: 정우, feature

#45 Refactor: move to layered architecture
  src/main/java/com/sooum/core/domain/member/controller/MemberAuthController.java
  src/main/java/com/sooum/core/domain/member/exception/MemberNotFoundException.java
  src/main/java/com/sooum/core/domain/member/service/MemberGetService.java
  src/main/java/com/sooum/core/domain/member/service/MemberInfoService.java
  src/main/java/com/sooum/core/domain/member/service/MemberSaveService.java
  src/main/java/com/sooum/core/domain/member/service/MemberService.java
  src/main/java/com/sooum/core/domain/member/service/PolicyService.java
  src/main/java/com/sooum/core/domain/member/service/RefreshTokenService.java
  src/test/java/com/sooum/core/CoreApplicationTests.java
Labels: 경규, refactor

#55 Refactor: update distance api
  src/main/java/com/sooum/core/domain/card/controller/DistanceCardController.java
  src/main/java/com/sooum/core/domain/card/service/DistanceFeedService.java
  src/main/java/com/sooum/core/global/util/DistanceUtils.java
Labels: 지원, refactor

#61 Feat: imei rsa decoding
  src/main/java/com/sooum/core/domain/member/controller/MemberAuthController.java
  src/main/java/com/sooum/core/domain/member/dto/AuthDTO.java
  src/main/java/com/sooum/core/domain/member/entity/Member.java
  src/main/java/com/sooum/core/domain/member/entity/Role.java
  src/main/java/com/sooum/core/domain/member/mapper/MemberMapper.java
  src/main/java/com/sooum/core/domain/member/service/BlacklistService.java
  src/main/java/com/sooum/core/domain/member/service/MemberInfoService.java
  src/main/java/com/sooum/core/domain/member/service/MemberService.java
  src/main/java/com/sooum/core/domain/rsa/entity/Rsa.java
  src/main/java/com/sooum/core/domain/rsa/exception/RsaDecodeException.java
  src/main/java/com/sooum/core/domain/rsa/exception/RsaGenerateException.java
  src/main/java/com/sooum/core/domain/rsa/repository/RsaRepository.java
  src/main/java/com/sooum/core/domain/rsa/service/RsaService.java
  src/main/java/com/sooum/core/global/auth/interceptor/JwtBlacklistInterceptor.java
  src/main/java/com/sooum/core/global/config/jwt/InvalidTokenException.java
  src/main/java/com/sooum/core/global/config/jwt/JwtAuthenticationFilter.java
  src/main/java/com/sooum/core/global/config/jwt/TokenProvider.java
  src/main/java/com/sooum/core/global/config/mvc/WebMvcConfig.java
  src/main/java/com/sooum/core/global/config/redis/RedisConfig.java
  src/main/java/com/sooum/core/global/config/security/SecurityConfig.java
  src/main/java/com/sooum/core/global/rsa/RsaProvider.java
  src/main/resources/application.yml
Labels: 경규, feature

#62 Feat: block member api
  src/main/java/com/sooum/core/domain/block/controller/BlockController.java
  src/main/java/com/sooum/core/domain/block/dto/BlockDto.java
  src/main/java/com/sooum/core/domain/block/repository/BlockRepository.java
  src/main/java/com/sooum/core/domain/block/service/BlockMemberService.java
  src/main/java/com/sooum/core/global/exceptionmessage/ExceptionMessage.java
Labels: 지원, feature

#69 chore:exception message 변경
  src/main/java/com/sooum/core/domain/card/service/CommentLikeService.java
  src/main/java/com/sooum/core/domain/card/service/FeedLikeService.java
  src/main/java/com/sooum/core/global/exceptionmessage/ExceptionMessage.java
Labels: 호왕, chore

#63 refactor<PopularCardRepository>: 인기 있는 글 조회 쿼리 수정
  src/main/java/com/sooum/core/domain/card/dto/PopularCardDto.java
  src/main/java/com/sooum/core/domain/card/repository/PopularFeedRepository.java
  src/main/java/com/sooum/core/domain/card/service/PopularFeedService.java
  src/test/java/com/sooum/core/domain/card/controller/CommentCardControllerTest.java
  src/test/java/com/sooum/core/domain/card/controller/PopularFeedControllerTest.java
  src/test/java/com/sooum/core/domain/card/repository/PopularFeedRepositoryTest.java
  src/test/java/com/sooum/core/domain/card/service/PopularFeedServiceTest.java
Labels: 호왕, refactor

#72 feat/기존 기본 예외 메시지를 규약 메시지로 변경하여 반환하도록 변경.
  build.gradle
  src/main/java/com/sooum/core/domain/card/repository/PopularFeedRepository.java
  src/main/java/com/sooum/core/domain/card/service/CommentCardService.java
  src/main/java/com/sooum/core/domain/card/service/FeedCardService.java
  src/main/java/com/sooum/core/domain/card/service/PopularFeedService.java
Labels: 정우, feature

#76 Refactor: apply hateoas
  src/main/java/com/sooum/core/domain/member/controller/MemberAuthController.java
  src/main/java/com/sooum/core/domain/member/dto/AuthDTO.java
  src/main/java/com/sooum/core/domain/member/service/MemberInfoService.java
  src/main/java/com/sooum/core/domain/rsa/service/RsaService.java
Labels: 경규, refactor

#75 Refactor: Extract conditional logic into methods
  src/main/java/com/sooum/core/domain/block/service/BlockMemberService.java
  src/main/java/com/sooum/core/domain/card/controller/FeedCardController.java
  src/main/java/com/sooum/core/domain/card/service/CommentCardService.java
  src/main/java/com/sooum/core/domain/card/service/FeedService.java
  src/test/java/com/sooum/core/domain/card/service/FeedServiceTest.java
Labels: 정우, refactor

#79 Refactor: rsa key generate latency
  build.gradle
  src/main/java/com/sooum/core/CoreApplication.java
  src/main/java/com/sooum/core/domain/member/controller/MemberAuthController.java
  src/main/java/com/sooum/core/domain/member/dto/AuthDTO.java
  src/main/java/com/sooum/core/domain/member/service/MemberInfoService.java
  src/main/java/com/sooum/core/domain/rsa/batch/RsaKeyGenerateConfig.java
  src/main/java/com/sooum/core/domain/rsa/repository/RsaRepository.java
  src/main/java/com/sooum/core/domain/rsa/service/RsaService.java
  src/main/java/com/sooum/core/global/config/jwt/TokenProvider.java
Labels: 경규, feature

#82 refactor: commentCardRepository query modified
  src/main/java/com/sooum/core/domain/card/repository/CommentCardRepository.java
  src/main/java/com/sooum/core/domain/card/service/CommentCardService.java
Labels: bug, 정우, refactor

#86 refactor: 거리순 피드 가져오기 로직 수정
  src/main/java/com/sooum/core/domain/card/repository/FeedCardRepository.java
  src/main/java/com/sooum/core/domain/card/service/DistanceFeedService.java
Labels: 지원, refactor

#80 Refactor: redis backup storage
  src/main/java/com/sooum/core/domain/member/batch/BlacklistFetchConfig.java
  src/main/java/com/sooum/core/domain/member/controller/MemberAuthController.java
  src/main/java/com/sooum/core/domain/member/entity/Blacklist.java
  src/main/java/com/sooum/core/domain/member/repository/BlacklistRepository.java
  src/main/java/com/sooum/core/domain/member/service/BlacklistService.java
Labels: 경규, refactor

#93 feat: 피드카드 조회 시 나만 보기 카드 제거 조건 추가
  src/main/java/com/sooum/core/domain/card/repository/FeedCardRepository.java
Labels: 정우, feature

#94 refactor: 카드 공개 여부 필드는 피드카드에만 존재하도록 변경
  src/main/java/com/sooum/core/domain/card/entity/Card.java
  src/main/java/com/sooum/core/domain/card/entity/CommentCard.java
  src/main/java/com/sooum/core/domain/card/entity/FeedCard.java
Labels: 정우, refactor

#97 refactor: long -> string으로 모든 카드 Id가 string으로 반환되도록 변경
  src/main/java/com/sooum/core/domain/card/dto/CardDto.java
  src/main/java/com/sooum/core/domain/card/dto/CommentDto.java
  src/main/java/com/sooum/core/domain/card/dto/DistanceCardDto.java
  src/main/java/com/sooum/core/domain/card/dto/LatestFeedCardDto.java
  src/main/java/com/sooum/core/domain/card/dto/PopularCardRetrieve.java
  src/main/java/com/sooum/core/domain/card/entity/FeedCard.java
  src/main/java/com/sooum/core/domain/card/entity/font/Font.java
  src/main/java/com/sooum/core/domain/card/service/CommentInfoService.java
  src/main/java/com/sooum/core/domain/card/service/DistanceFeedService.java
  src/main/java/com/sooum/core/domain/card/service/LatestFeedService.java
  src/main/java/com/sooum/core/domain/card/service/PopularFeedService.java
  src/main/java/com/sooum/core/global/util/NextPageLinkGenerator.java
Labels: 정우, refactor

#83 feat: 피드카드 상세조회 API 구현
  src/main/java/com/sooum/core/domain/card/controller/FeedCardController.java
  src/main/java/com/sooum/core/domain/card/dto/CardDetailDto.java
  src/main/java/com/sooum/core/domain/card/dto/CommentDetailCardDto.java
  src/main/java/com/sooum/core/domain/card/dto/FeedDetailCardDto.java
  src/main/java/com/sooum/core/domain/card/repository/FeedLikeRepository.java
  src/main/java/com/sooum/core/domain/card/service/DetailFeedService.java
  src/main/java/com/sooum/core/domain/card/service/FeedLikeService.java
  src/main/java/com/sooum/core/domain/card/service/FeedService.java
  src/main/java/com/sooum/core/domain/member/dto/MemberDto.java
  src/main/java/com/sooum/core/domain/member/entity/Member.java
  src/main/java/com/sooum/core/domain/member/service/MemberInfoService.java
  src/main/java/com/sooum/core/domain/tag/controller/TagController.java
  src/main/java/com/sooum/core/domain/tag/dto/TagDto.java
  src/main/java/com/sooum/core/domain/tag/repository/CommentTagRepository.java
  src/main/java/com/sooum/core/domain/tag/repository/FeedTagRepository.java
  src/main/java/com/sooum/core/domain/tag/service/FeedTagService.java
  src/main/java/com/sooum/core/domain/tag/service/TagService.java
  src/main/java/com/sooum/core/global/exceptionmessage/ExceptionMessage.java
  src/main/java/com/sooum/core/global/util/NextPageLinkGenerator.java
Labels: 지원, feature
