Repository prj154654168/Sooum-BE, pull requests merged in 2024-11, with the labels that each got.

#196 refactor/rsa key null일때 rds에서 가져오도록 변경
  boot/external-api/src/main/java/com/sooum/api/rsa/service/RsaUseCase.java
Labels: 정우, refactor

#193 feat: 사용안하는 이미지 삭제 batch 개발 및 cloud 모듈화
  boot/batch/build.gradle
  boot/batch/src/main/java/com/sooum/BatchApplication.java
  boot/batch/src/main/java/com/sooum/batch/img/batch/DeleteCardImgBatch.java
  boot/batch/src/main/java/com/sooum/batch/img/batch/DeleteProfileImgBatch.java
  boot/batch/src/main/java/com/sooum/batch/img/service/ImgService.java
  boot/batch/src/main/java/com/sooum/batch/member/BlacklistFetchConfig.java
  boot/batch/src/main/java/com/sooum/batch/rsa/RsaKeyGenerateConfig.java
  boot/external-api/build.gradle
  boot/external-api/src/main/java/com/sooum/ExternalApiApplication.java
  boot/external-api/src/main/java/com/sooum/api/card/dto/CreateCardDto.java
  boot/external-api/src/main/java/com/sooum/api/card/dto/CreateCommentDto.java
  boot/external-api/src/main/java/com/sooum/api/card/dto/CreateFeedCardDto.java
  boot/external-api/src/main/java/com/sooum/api/card/service/CommentInfoService.java
  boot/external-api/src/main/java/com/sooum/api/card/service/DetailFeedService.java
  boot/external-api/src/main/java/com/sooum/api/card/service/DistanceFeedService.java
  boot/external-api/src/main/java/com/sooum/api/card/service/FeedCardUseCase.java
  boot/external-api/src/main/java/com/sooum/api/card/service/FeedService.java
  boot/external-api/src/main/java/com/sooum/api/card/service/LatestFeedService.java
  boot/external-api/src/main/java/com/sooum/api/card/service/PopularRetrieveService.java
  boot/external-api/src/main/java/com/sooum/api/card/service/TagFeedInfoService.java
  boot/external-api/src/main/java/com/sooum/api/img/service/AWSImgService.java
  boot/external-api/src/main/java/com/sooum/api/img/service/ImgService.java
  boot/external-api/src/main/java/com/sooum/api/img/service/LocalImgService.java
  boot/external-api/src/main/java/com/sooum/api/member/controller/MemberAuthController.java
  boot/external-api/src/main/java/com/sooum/api/member/controller/ProfileController.java
  boot/external-api/src/main/java/com/sooum/api/member/service/MemberUseCase.java
  boot/external-api/src/main/java/com/sooum/api/rsa/service/RsaUseCase.java
  boot/external-api/src/main/java/com/sooum/api/tag/service/FavoriteTagUseCase.java
  boot/external-api/src/main/java/com/sooum/global/auth/interceptor/JwtBlacklistInterceptor.java
  boot/external-api/src/main/java/com/sooum/global/config/jwt/TokenProvider.java
  boot/external-api/src/main/java/com/sooum/global/config/security/SecurityConfig.java
  cloud/build.gradle
  cloud/src/main/java/com/sooum/client/aws/rekognition/RekognitionConfig.java
  cloud/src/main/java/com/sooum/client/aws/s3/RekognitionService.java
  cloud/src/main/java/com/sooum/client/aws/s3/S3Service.java
  cloud/src/main/java/com/sooum/config/aws/s3/S3Config.java
  cloud/src/main/resources/application.yml
  data/core-data/src/main/java/com/sooum/data/card/entity/Card.java
  data/core-data/src/main/java/com/sooum/data/card/entity/CommentCard.java
  data/core-data/src/main/java/com/sooum/data/card/entity/FeedCard.java
  data/core-data/src/main/java/com/sooum/data/card/entity/imgtype/CardImgType.java
  data/core-data/src/main/java/com/sooum/data/card/service/PopularFeedService.java
  data/core-data/src/main/java/com/sooum/data/card/service/TagFeedService.java
  data/core-data/src/main/java/com/sooum/data/img/entity/CardImg.java
  data/core-data/src/main/java/com/sooum/data/img/entity/Img.java
  data/core-data/src/main/java/com/sooum/data/img/entity/ProfileImg.java
  data/core-data/src/main/java/com/sooum/data/img/entity/UserUploadPic.java
  data/core-data/src/main/java/com/sooum/data/img/repository/CardImgRepository.java
  data/core-data/src/main/java/com/sooum/data/img/repository/ProfileImgRepository.java
  data/core-data/src/main/java/com/sooum/data/img/service/CardImgService.java
  data/core-data/src/main/java/com/sooum/data/img/service/ProfileImgService.java
  data/core-data/src/main/java/com/sooum/data/img/service/UserImgService.java
  data/core-data/src/main/java/com/sooum/data/member/service/AccountTransferService.java
  data/core-data/src/main/java/com/sooum/data/tag/entity/CachedTag.java
  data/core-data/src/main/java/com/sooum/data/tag/repository/CachedTagRepository.java
  data/core-data/src/main/java/com/sooum/data/tag/service/FavoriteTagService.java
  settings.gradle
Labels: 호왕, feature

#197 Refactor/profile update
  boot/external-api/src/main/java/com/sooum/api/card/service/FeedService.java
  boot/external-api/src/main/java/com/sooum/api/img/service/AWSImgService.java
  boot/external-api/src/main/java/com/sooum/api/img/service/ImgService.java
  boot/external-api/src/main/java/com/sooum/api/img/service/LocalImgService.java
  boot/external-api/src/main/java/com/sooum/api/member/service/ProfileService.java
  cloud/src/main/java/com/sooum/client/aws/rekognition/RekognitionService.java
  cloud/src/main/java/com/sooum/client/aws/s3/S3Service.java
  cloud/src/main/java/com/sooum/config/aws/rekognition/RekognitionConfig.java
  data/core-data/src/main/java/com/sooum/data/img/entity/UserUploadPic.java
Labels: fix, 호왕, chore

#202 yml import
  boot/external-api/src/main/resources/application.yml
  cloud/src/main/resources/application-cloud.yml
Labels: 정우, chore

#200 Refactor/token reissue api
  boot/external-api/src/main/java/com/sooum/api/block/service/BlackListUseCase.java
  boot/external-api/src/main/java/com/sooum/api/member/service/MemberInfoService.java
  boot/external-api/src/main/java/com/sooum/api/report/controller/ReportController.java
  boot/external-api/src/main/java/com/sooum/api/report/service/ReportService.java
  boot/external-api/src/main/java/com/sooum/global/auth/interceptor/JwtBlacklistInterceptor.java
  boot/external-api/src/main/java/com/sooum/global/config/jwt/JwtAuthenticationFilter.java
  boot/external-api/src/main/java/com/sooum/global/config/jwt/TokenProvider.java
  boot/external-api/src/main/java/com/sooum/global/config/security/SecurityConfig.java
  data/core-data/src/main/java/com/sooum/data/member/entity/Member.java
  data/core-data/src/main/java/com/sooum/data/member/entity/RefreshToken.java
  data/core-data/src/main/java/com/sooum/data/member/service/RefreshTokenService.java
Labels: 경규, refactor

#204 refactor: card image user logic
  boot/external-api/src/main/java/com/sooum/api/card/service/FeedService.java
  data/core-data/src/main/java/com/sooum/data/img/entity/CardImg.java
  data/core-data/src/main/java/com/sooum/data/img/repository/CardImgRepository.java
  data/core-data/src/main/java/com/sooum/data/img/service/CardImgService.java
Labels: refactor

#205 Feat:delete member api
  boot/external-api/src/main/java/com/sooum/api/member/controller/MemberController.java
  boot/external-api/src/main/java/com/sooum/api/member/service/MemberWithdrawalService.java
  data/core-data/src/main/java/com/sooum/data/block/repository/BlockRepository.java
  data/core-data/src/main/java/com/sooum/data/block/service/BlockMemberService.java
  data/core-data/src/main/java/com/sooum/data/card/entity/Card.java
  data/core-data/src/main/java/com/sooum/data/card/repository/CommentCardRepository.java
  data/core-data/src/main/java/com/sooum/data/card/repository/CommentLikeRepository.java
  data/core-data/src/main/java/com/sooum/data/card/repository/FeedCardRepository.java
  data/core-data/src/main/java/com/sooum/data/card/repository/FeedLikeRepository.java
  data/core-data/src/main/java/com/sooum/data/card/repository/PopularFeedRepository.java
  data/core-data/src/main/java/com/sooum/data/card/service/CommentCardService.java
  data/core-data/src/main/java/com/sooum/data/card/service/CommentLikeService.java
  data/core-data/src/main/java/com/sooum/data/card/service/FeedCardService.java
  data/core-data/src/main/java/com/sooum/data/card/service/FeedLikeService.java
  data/core-data/src/main/java/com/sooum/data/card/service/PopularFeedService.java
  data/core-data/src/main/java/com/sooum/data/follow/repository/FollowRepository.java
  data/core-data/src/main/java/com/sooum/data/follow/service/FollowService.java
  data/core-data/src/main/java/com/sooum/data/img/repository/CardImgRepository.java
  data/core-data/src/main/java/com/sooum/data/img/repository/ProfileImgRepository.java
  data/core-data/src/main/java/com/sooum/data/img/service/CardImgService.java
  data/core-data/src/main/java/com/sooum/data/img/service/ProfileImgService.java
  data/core-data/src/main/java/com/sooum/data/member/repository/AccountTransferRepository.java
  data/core-data/src/main/java/com/sooum/data/member/repository/PolicyTermRepository.java
  data/core-data/src/main/java/com/sooum/data/member/repository/RefreshTokenRepository.java
  data/core-data/src/main/java/com/sooum/data/member/service/AccountTransferService.java
  data/core-data/src/main/java/com/sooum/data/member/service/BlacklistService.java
  data/core-data/src/main/java/com/sooum/data/member/service/MemberService.java
  data/core-data/src/main/java/com/sooum/data/member/service/PolicyService.java
  data/core-data/src/main/java/com/sooum/data/member/service/RefreshTokenService.java
  data/core-data/src/main/java/com/sooum/data/report/repository/CommentReportRepository.java
  data/core-data/src/main/java/com/sooum/data/report/repository/FeedReportRepository.java
  data/core-data/src/main/java/com/sooum/data/report/service/CommentReportService.java
  data/core-data/src/main/java/com/sooum/data/report/service/FeedReportService.java
  data/core-data/src/main/java/com/sooum/data/suspended/entity/Suspended.java
  data/core-data/src/main/java/com/sooum/data/suspended/repository/SuspendedRepository.java
  data/core-data/src/main/java/com/sooum/data/suspended/service/SuspendedService.java
  data/core-data/src/main/java/com/sooum/data/tag/repository/FavoriteTagRepository.java
  data/core-data/src/main/java/com/sooum/data/tag/service/FavoriteTagService.java
  data/core-data/src/main/java/com/sooum/data/visitor/repository/VisitorRepository.java
  data/core-data/src/main/java/com/sooum/data/visitor/service/VisitorService.java
Labels: feature

#209 fix: 좋아요 관련 메소드 수정
  data/core-data/src/main/java/com/sooum/data/card/repository/CommentLikeRepository.java
  data/core-data/src/main/java/com/sooum/data/card/repository/FeedLikeRepository.java
  data/core-data/src/main/java/com/sooum/data/card/service/CommentLikeService.java
  data/core-data/src/main/java/com/sooum/data/card/service/FeedLikeService.java
Labels: fix, 호왕

#211 fix: 프로필 업데이트 서비스 메소드 수정
  boot/external-api/src/main/java/com/sooum/api/card/service/FeedService.java
  boot/external-api/src/main/java/com/sooum/api/img/service/AWSImgService.java
  boot/external-api/src/main/java/com/sooum/api/img/service/ImgService.java
  boot/external-api/src/main/java/com/sooum/api/member/service/ProfileService.java
  cloud/src/main/java/com/sooum/client/aws/s3/S3Service.java
  data/core-data/src/main/java/com/sooum/data/member/entity/Member.java
Labels: fix, 호왕

#214 카드 삭제 isDelete 상태 변경에서 진짜 삭제로 수정
  boot/external-api/src/main/java/com/sooum/api/card/service/FeedService.java
Labels: 정우, refactor

#212 story deletion without img and notification
  boot/batch/src/main/java/com/sooum/BatchApplication.java
  boot/batch/src/main/java/com/sooum/batch/card/batch/StoryDeleteBatchConfig.java
  boot/batch/src/main/java/com/sooum/batch/card/batch/dto/CommentRelatedEntitiesDeletionDto.java
  boot/batch/src/main/java/com/sooum/batch/card/batch/dto/FeedRelatedEntitiesDeletionDto.java
  boot/batch/src/main/java/com/sooum/batch/card/batch/repository/CommentCardBatchRepository.java
  boot/batch/src/main/java/com/sooum/batch/card/batch/repository/CommentLikeBatchRepository.java
  boot/batch/src/main/java/com/sooum/batch/card/batch/repository/CommentReportBatchRepository.java
  boot/batch/src/main/java/com/sooum/batch/card/batch/repository/FeedCardBatchRepository.java
  boot/batch/src/main/java/com/sooum/batch/card/batch/repository/FeedLikeBatchRepository.java
  boot/batch/src/main/java/com/sooum/batch/card/batch/repository/FeedReportBatchRepository.java
  boot/batch/src/main/java/com/sooum/batch/img/batch/DeleteCardImgBatch.java
  boot/batch/src/main/java/com/sooum/batch/img/batch/DeleteProfileImgBatch.java
  boot/batch/src/main/resources/application.yml
Labels: 정우, feature

#218 Refactor: Transfer batch code
  boot/batch/build.gradle
  boot/batch/src/main/java/com/sooum/batch/config/RedisConfig.java
  boot/batch/src/main/java/com/sooum/batch/member/BlacklistFetchConfig.java
  boot/batch/src/main/java/com/sooum/batch/rsa/RsaKeyGenerateConfig.java
  boot/batch/src/main/java/com/sooum/batch/rsa/service/RsaBatchService.java
  boot/external-api/src/main/java/com/sooum/api/card/service/FeedService.java
  boot/external-api/src/main/java/com/sooum/api/member/service/BlackListUseCase.java
  boot/external-api/src/main/java/com/sooum/api/rsa/service/RsaUseCase.java
  boot/external-api/src/main/java/com/sooum/global/auth/interceptor/JwtBlacklistInterceptor.java
  boot/external-api/src/main/java/com/sooum/global/rsa/RsaProvider.java
  data/core-data/src/main/java/com/sooum/data/rsa/service/RsaService.java
Labels: 경규, refactor

#216 refactor: 이전카드 조회시 삭제되었을 경우 id -1로 반환
  boot/external-api/src/main/java/com/sooum/api/card/service/DetailFeedService.java
  boot/external-api/src/main/java/com/sooum/api/card/service/FeedService.java
  data/core-data/src/main/java/com/sooum/data/card/service/CommentCardService.java
  data/core-data/src/main/java/com/sooum/data/card/service/FeedCardService.java
Labels: 지원, refactor

#219 refactor: card hard delete에 따른 유저 탈퇴로직 수정
  boot/external-api/src/main/java/com/sooum/api/member/service/MemberWithdrawalService.java
  data/core-data/src/main/java/com/sooum/data/card/repository/CommentCardRepository.java
  data/core-data/src/main/java/com/sooum/data/card/repository/FeedCardRepository.java
  data/core-data/src/main/java/com/sooum/data/card/service/CommentCardService.java
  data/core-data/src/main/java/com/sooum/data/card/service/FeedCardService.java
  data/core-data/src/main/java/com/sooum/data/tag/repository/CommentTagRepository.java
  data/core-data/src/main/java/com/sooum/data/tag/repository/FeedTagRepository.java
  data/core-data/src/main/java/com/sooum/data/tag/service/CommentTagService.java
  data/core-data/src/main/java/com/sooum/data/tag/service/FeedTagService.java
Labels: refactor

#223 Feat/slack alert
  boot/batch/build.gradle
  boot/batch/src/main/java/com/sooum/batch/img/batch/DeleteCardImgBatch.java
  boot/batch/src/main/java/com/sooum/batch/img/batch/DeleteProfileImgBatch.java
  boot/batch/src/main/resources/application.yml
  boot/batch/src/main/resources/logback-spring.xml
  boot/external-api/build.gradle
  boot/external-api/src/main/java/com/sooum/api/report/service/ReportService.java
  boot/external-api/src/main/java/com/sooum/global/advice/ValidExceptionHandler.java
  boot/external-api/src/main/java/com/sooum/global/aop/SlackAspect.java
  boot/external-api/src/main/java/com/sooum/global/slack/dto/RequestDto.java
  boot/external-api/src/main/java/com/sooum/global/slack/filter/ContentCachingFilter.java
  boot/external-api/src/main/java/com/sooum/global/slack/service/SlackService.java
  boot/external-api/src/main/resources/application.yml
  data/core-data/src/main/java/com/sooum/data/card/service/CommentCardService.java
  data/core-data/src/main/java/com/sooum/data/card/service/CommentLikeService.java
  data/core-data/src/main/java/com/sooum/data/card/service/FeedCardService.java
  data/core-data/src/main/java/com/sooum/data/card/service/FeedLikeService.java
  data/core-data/src/main/java/com/sooum/data/member/service/AccountTransferService.java
  data/core-data/src/main/java/com/sooum/data/member/service/MemberService.java
  data/core-data/src/main/java/com/sooum/data/member/service/RefreshTokenService.java
  data/core-data/src/main/java/com/sooum/data/rsa/service/RsaService.java
  data/core-data/src/main/java/com/sooum/data/tag/service/TagService.java
Labels: 호왕, feature

#227 Refactor: sign up logic
  boot/external-api/src/main/java/com/sooum/api/member/service/MemberInfoService.java
  data/core-data/src/main/java/com/sooum/data/member/repository/MemberRepository.java
  data/core-data/src/main/java/com/sooum/data/member/service/MemberService.java
Labels: 경규, refactor

#228 feature: check suspension member
  boot/external-api/src/main/java/com/sooum/api/member/controller/MemberController.java
  boot/external-api/src/main/java/com/sooum/global/config/security/SecurityConfig.java
  data/core-data/src/main/java/com/sooum/data/suspended/repository/SuspendedRepository.java
  data/core-data/src/main/java/com/sooum/data/suspended/service/SuspendedService.java
Labels: feature

#229 Refactor/card summary
  boot/external-api/src/main/java/com/sooum/api/card/dto/CardSummary.java
  boot/external-api/src/main/java/com/sooum/api/card/service/CardService.java
  data/core-data/src/main/java/com/sooum/data/block/service/BlockMemberService.java
  data/core-data/src/main/java/com/sooum/data/card/service/CommentLikeService.java
  data/core-data/src/main/java/com/sooum/data/card/service/FeedLikeService.java
  data/core-data/src/main/java/com/sooum/data/tag/service/FavoriteTagService.java
Labels: 호왕, refactor

#231 refactor: 댓글 카드, 태그 카드 조회 로직 최적화
  boot/external-api/src/main/java/com/sooum/api/card/service/CommentInfoService.java
  boot/external-api/src/main/java/com/sooum/api/card/service/LatestFeedService.java
  boot/external-api/src/main/java/com/sooum/api/card/service/TagFeedInfoService.java
  data/core-data/src/main/java/com/sooum/data/card/repository/CommentCardRepository.java
  data/core-data/src/main/java/com/sooum/data/card/service/CommentCardService.java
  data/core-data/src/main/java/com/sooum/data/card/service/TagFeedService.java
  data/core-data/src/main/java/com/sooum/data/tag/repository/FeedTagRepository.java
Labels: 호왕, refactor

#232 refactor/ prevent self block
  data/core-data/src/main/java/com/sooum/data/block/service/BlockMemberService.java
Labels: 지원, refactor

#234 구분자 추가
  boot/external-api/src/main/java/com/sooum/global/regex/BadWords.java
Labels: fix, 정우

#243 회원가입 로직 토큰 중복 발급 오류 수정
  boot/external-api/src/main/java/com/sooum/api/member/service/MemberInfoService.java
  boot/external-api/src/main/java/com/sooum/global/advice/ValidExceptionHandler.java
  boot/external-api/src/main/java/com/sooum/global/config/jwt/JwtAuthenticationFilter.java
Labels: fix, 정우

#250 토큰 인증 필요없는 uri는 헤더에 토큰 뭘 넣든 상관없게 변경
  boot/external-api/src/main/java/com/sooum/global/config/jwt/JwtAuthenticationFilter.java
  boot/external-api/src/main/java/com/sooum/global/config/mvc/WebMvcConfig.java
Labels: 정우, refactor

#251 Fix: block api change dto
  boot/external-api/src/main/java/com/sooum/api/block/controller/BlockController.java
  boot/external-api/src/main/java/com/sooum/api/block/dto/BlockDto.java
Labels: fix, 지원
