Repository prj154654168/Sooum-BE, pull requests merged in 2024-10, with the labels that each got.

#104 refactor<CardSummary>: 댓글수 조회 API 변경
  src/main/java/com/sooum/core/domain/card/controller/CardController.java
  src/main/java/com/sooum/core/domain/card/controller/CommentCardController.java
  src/main/java/com/sooum/core/domain/card/dto/CardSummary.java
  src/main/java/com/sooum/core/domain/card/dto/CommentDto.java
  src/main/java/com/sooum/core/domain/card/repository/CommentLikeRepository.java
  src/main/java/com/sooum/core/domain/card/service/CardService.java
  src/main/java/com/sooum/core/domain/card/service/CommentCardService.java
  src/main/java/com/sooum/core/domain/card/service/CommentLikeService.java
  src/main/java/com/sooum/core/domain/card/service/FeedLikeService.java
  src/test/java/com/sooum/core/domain/card/controller/FeedCardControllerTest.java
  src/test/java/com/sooum/core/domain/card/repository/CardLikeRepositoryTest.java
  src/test/java/com/sooum/core/domain/card/repository/CommentCardRepositoryTest.java
  src/test/java/com/sooum/core/domain/card/repository/PopularFeedRepositoryTest.java
  src/test/java/com/sooum/core/domain/card/service/CardServiceTest.java
  src/test/java/com/sooum/core/domain/card/service/CommentCardServiceTest.java
  src/test/java/com/sooum/core/domain/card/service/CommentLikeServiceTest.java
  src/test/java/com/sooum/core/domain/card/service/FeedLikeServiceTest.java
  src/test/java/com/sooum/core/domain/card/service/FeedStaticServiceTest.java
  src/test/java/com/sooum/core/domain/card/service/PopularFeedServiceTest.java
Labels: 호왕, refactor

#102 Feat/img retrieve and create
  src/main/java/com/sooum/core/domain/card/repository/CommentCardRepository.java
  src/main/java/com/sooum/core/domain/card/repository/PopularFeedRepository.java
  src/main/java/com/sooum/core/domain/card/service/CommentCardService.java
  src/main/java/com/sooum/core/domain/card/service/CommentInfoService.java
  src/main/java/com/sooum/core/domain/card/service/DetailFeedService.java
  src/main/java/com/sooum/core/domain/card/service/DistanceFeedService.java
  src/main/java/com/sooum/core/domain/card/service/LatestFeedService.java
  src/main/java/com/sooum/core/domain/card/service/PopularFeedService.java
  src/main/java/com/sooum/core/domain/img/controller/ImgController.java
  src/main/java/com/sooum/core/domain/img/dto/ImgUrlInfo.java
  src/main/java/com/sooum/core/domain/img/service/ImgService.java
  src/main/java/com/sooum/core/domain/img/service/LocalImgService.java
  src/main/java/com/sooum/core/global/config/security/SecurityConfig.java
  src/main/resources/application.yml
  src/test/java/com/sooum/core/domain/card/service/PopularFeedServiceTest.java
  src/test/java/com/sooum/core/domain/img/service/LocalImgServiceTest.java
  src/test/resources/application.yml
Labels: 호왕, feature

#103 refactor<CardLikeService>: 피드/답글 카드로 나눠져 있는 API 통합
  src/main/java/com/sooum/core/domain/card/controller/CommentCardController.java
  src/main/java/com/sooum/core/domain/card/controller/FeedCardController.java
  src/main/java/com/sooum/core/domain/card/service/FeedLikeService.java
  src/test/java/com/sooum/core/domain/card/controller/CommentCardControllerTest.java
  src/test/java/com/sooum/core/domain/card/controller/FeedCardControllerTest.java
  src/test/java/com/sooum/core/domain/card/repository/PopularFeedRepositoryTest.java
Labels: 호왕, refactor

#107 feat: create card api
  src/main/java/com/sooum/core/domain/card/controller/FeedCardController.java
  src/main/java/com/sooum/core/domain/card/dto/CreateCardDto.java
  src/main/java/com/sooum/core/domain/card/dto/CreateCommentDto.java
  src/main/java/com/sooum/core/domain/card/dto/CreateFeedCardDto.java
  src/main/java/com/sooum/core/domain/card/entity/fontsize/FontSize.java
  src/main/java/com/sooum/core/domain/card/service/CommentCardService.java
  src/main/java/com/sooum/core/domain/card/service/DetailFeedService.java
  src/main/java/com/sooum/core/domain/card/service/FeedCardService.java
  src/main/java/com/sooum/core/domain/card/service/FeedService.java
  src/main/java/com/sooum/core/domain/tag/repository/TagRepository.java
  src/main/java/com/sooum/core/domain/tag/service/CommentTagService.java
  src/main/java/com/sooum/core/domain/tag/service/FeedTagService.java
  src/main/java/com/sooum/core/domain/tag/service/TagService.java
  src/main/java/com/sooum/core/global/exceptionmessage/ExceptionMessage.java
Labels: 지원, feature

#114 Feat/tag card retrieve
  src/main/java/com/sooum/core/domain/card/controller/CardController.java
  src/main/java/com/sooum/core/domain/card/controller/FeedCardController.java
  src/main/java/com/sooum/core/domain/card/dto/TagFeedCardDto.java
  src/main/java/com/sooum/core/domain/card/service/TagFeedService.java
  src/main/java/com/sooum/core/domain/tag/controller/TagController.java
  src/main/java/com/sooum/core/domain/tag/dto/TagDto.java
  src/main/java/com/sooum/core/domain/tag/repository/FavoriteTagRepository.java
  src/main/java/com/sooum/core/domain/tag/repository/FeedTagRepository.java
  src/main/java/com/sooum/core/domain/tag/repository/TagRepository.java
  src/main/java/com/sooum/core/domain/tag/service/FavoriteTagService.java
  src/main/java/com/sooum/core/domain/tag/service/TagService.java
  src/main/java/com/sooum/core/global/exceptionmessage/ExceptionMessage.java
  src/test/java/com/sooum/core/domain/card/controller/CardControllerTest.java
  src/test/java/com/sooum/core/domain/card/controller/FeedCardControllerTest.java
  src/test/java/com/sooum/core/domain/card/service/CardServiceTest.java
  src/test/java/com/sooum/core/domain/card/service/CommentCardServiceTest.java
  src/test/java/com/sooum/core/domain/card/service/FeedServiceTest.java
  src/test/java/com/sooum/core/domain/tag/repository/FavoriteTagRepositoryTest.java
  src/test/java/com/sooum/core/domain/tag/repository/FeedTagRepositoryTest.java
  src/test/java/com/sooum/core/domain/tag/service/FavoriteTagServiceTest.java
Labels: 호왕, feature

#117 feat: presigned url로 변경
  build.gradle
  src/main/java/com/sooum/core/domain/img/controller/ImgController.java
  src/main/java/com/sooum/core/domain/img/service/AWSImgService.java
  src/main/java/com/sooum/core/domain/img/service/ImgService.java
  src/main/java/com/sooum/core/domain/img/service/LocalImgService.java
  src/main/java/com/sooum/core/global/config/s3/S3Config.java
  src/main/resources/application.yml
Labels: 정우, feature

#100 Feat: report api
  src/main/java/com/sooum/core/CoreApplication.java
  src/main/java/com/sooum/core/domain/card/repository/CommentCardRepository.java
  src/main/java/com/sooum/core/domain/card/repository/CommentLikeRepository.java
  src/main/java/com/sooum/core/domain/card/service/CommentCardService.java
  src/main/java/com/sooum/core/domain/card/service/CommentLikeService.java
  src/main/java/com/sooum/core/domain/member/entity/Blacklist.java
  src/main/java/com/sooum/core/domain/member/entity/Member.java
  src/main/java/com/sooum/core/domain/member/repository/PolicyRepository.java
  src/main/java/com/sooum/core/domain/member/service/BlacklistService.java
  src/main/java/com/sooum/core/domain/member/service/MemberInfoService.java
  src/main/java/com/sooum/core/domain/member/service/PolicyService.java
  src/main/java/com/sooum/core/domain/report/controller/ReportController.java
  src/main/java/com/sooum/core/domain/report/entity/CommentReport.java
  src/main/java/com/sooum/core/domain/report/exception/DuplicateReportException.java
  src/main/java/com/sooum/core/domain/report/repository/CommentReportRepository.java
  src/main/java/com/sooum/core/domain/report/repository/FeedReportRepository.java
  src/main/java/com/sooum/core/domain/report/service/CommentReportService.java
  src/main/java/com/sooum/core/domain/report/service/FeedReportService.java
  src/main/java/com/sooum/core/domain/report/service/ReportService.java
  src/main/java/com/sooum/core/domain/rsa/entity/Rsa.java
  src/main/java/com/sooum/core/domain/rsa/repository/RsaRepository.java
  src/main/java/com/sooum/core/domain/rsa/service/RsaService.java
  src/main/java/com/sooum/core/domain/tag/entity/Tag.java
  src/main/java/com/sooum/core/domain/tag/repository/CommentTagRepository.java
  src/main/java/com/sooum/core/domain/tag/repository/FeedTagRepository.java
  src/main/java/com/sooum/core/domain/tag/service/CommentTagService.java
  src/main/java/com/sooum/core/domain/tag/service/FeedTagService.java
  src/main/java/com/sooum/core/global/auth/interceptor/JwtBlacklistInterceptor.java
  src/main/java/com/sooum/core/global/config/jwt/TokenProvider.java
  src/main/java/com/sooum/core/global/config/mvc/WebMvcConfig.java
  src/main/java/com/sooum/core/global/config/redis/RedisConfig.java
Labels: 경규, feature

#112 Feat: search by hashtag
  build.gradle
  src/main/java/com/sooum/core/CoreApplication.java
  src/main/java/com/sooum/core/domain/card/dto/FeedCardDto.java
  src/main/java/com/sooum/core/domain/tag/batch/TagCacheConfig.java
  src/main/java/com/sooum/core/domain/tag/controller/TagController.java
  src/main/java/com/sooum/core/domain/tag/dto/TagDto.java
  src/main/java/com/sooum/core/domain/tag/entity/CachedTag.java
  src/main/java/com/sooum/core/domain/tag/entity/Tag.java
  src/main/java/com/sooum/core/domain/tag/repository/CachedTagRepository.java
  src/main/java/com/sooum/core/domain/tag/repository/TagRepository.java
  src/main/java/com/sooum/core/domain/tag/service/FeedTagService.java
  src/main/java/com/sooum/core/domain/tag/service/TagService.java
  src/main/java/com/sooum/core/global/regex/BadWordFiltering.java
  src/main/java/com/sooum/core/global/regex/BadWords.java
  src/main/resources/application.yml
Labels: 경규, feature

#119 추천 태그 조회 api
  src/main/java/com/sooum/core/domain/tag/controller/TagController.java
  src/main/java/com/sooum/core/domain/tag/dto/TagDto.java
  src/main/java/com/sooum/core/domain/tag/repository/FavoriteTagRepository.java
  src/main/java/com/sooum/core/domain/tag/repository/TagRepository.java
  src/main/java/com/sooum/core/domain/tag/service/FavoriteTagService.java
  src/main/java/com/sooum/core/domain/tag/service/RecommendTagService.java
  src/main/java/com/sooum/core/domain/tag/service/TagService.java
  src/main/java/com/sooum/core/global/util/NextPageLinkGenerator.java
Labels: 정우, feature

#128 Fix: create card api
  src/main/java/com/sooum/core/domain/card/service/FeedService.java
  src/main/java/com/sooum/core/global/exceptionmessage/ExceptionMessage.java
Labels: fix, 지원

#129 Refactor: Search Hashtag
  src/main/java/com/sooum/core/domain/tag/controller/TagController.java
  src/main/java/com/sooum/core/domain/tag/service/TagService.java
Labels: 경규, refactor

#133 refactor/tagDetail
  src/main/java/com/sooum/core/global/util/NextPageLinkGenerator.java
Labels: 정우, refactor

#134 Refactor/isStory delete
  src/main/java/com/sooum/core/domain/card/dto/DistanceCardDto.java
  src/main/java/com/sooum/core/domain/card/dto/FeedCardDto.java
  src/main/java/com/sooum/core/domain/card/dto/FeedDetailCardDto.java
  src/main/java/com/sooum/core/domain/card/dto/LatestFeedCardDto.java
  src/main/java/com/sooum/core/domain/card/dto/PopularCardRetrieve.java
  src/main/java/com/sooum/core/domain/card/service/CommentInfoService.java
  src/main/java/com/sooum/core/domain/card/service/DistanceFeedService.java
  src/main/java/com/sooum/core/domain/card/service/FeedService.java
  src/main/java/com/sooum/core/domain/card/service/LatestFeedService.java
  src/main/java/com/sooum/core/domain/card/service/PopularFeedService.java
  src/main/java/com/sooum/core/domain/card/service/TagFeedService.java
  src/main/java/com/sooum/core/domain/tag/controller/TagController.java
  src/main/java/com/sooum/core/domain/tag/repository/FavoriteTagRepository.java
  src/main/java/com/sooum/core/domain/tag/repository/FeedTagRepository.java
  src/main/java/com/sooum/core/domain/tag/service/FavoriteTagService.java
  src/test/java/com/sooum/core/domain/card/service/FeedStaticServiceTest.java
  src/test/java/com/sooum/core/domain/card/service/PopularFeedServiceTest.java
Labels: 호왕, refactor

#135 build: build task추가
  build.gradle
Labels: 호왕

#136 refactor: 요구 사항에 따른 data form 변경
  src/main/java/com/sooum/core/domain/card/controller/FeedCardController.java
  src/main/java/com/sooum/core/domain/card/dto/CardDetailDto.java
  src/main/java/com/sooum/core/domain/card/dto/CommentDetailCardDto.java
  src/main/java/com/sooum/core/domain/card/dto/FeedDetailCardDto.java
  src/main/java/com/sooum/core/domain/card/service/DetailFeedService.java
Labels: 지원, refactor

#138 feat: 팔로우 언팔로우 api
  src/main/java/com/sooum/core/domain/follow/controller/FollowController.java
  src/main/java/com/sooum/core/domain/follow/dto/FollowDto.java
  src/main/java/com/sooum/core/domain/follow/repository/FollowRepository.java
  src/main/java/com/sooum/core/domain/follow/service/FollowManagementService.java
  src/main/java/com/sooum/core/domain/follow/service/FollowService.java
  src/main/java/com/sooum/core/global/exceptionmessage/ExceptionMessage.java
Labels: 정우, feature

#140 Feat/block member api
  src/main/java/com/sooum/core/domain/block/controller/BlockController.java
  src/main/java/com/sooum/core/domain/block/repository/BlockRepository.java
  src/main/java/com/sooum/core/domain/block/service/BlockMemberService.java
Labels: 정우, feature

#142 feat/프로필 페이지의 방문자수와 팔로워,팔로잉,닉네임 등 정보 조회 api
  src/main/java/com/sooum/core/domain/card/repository/FeedCardRepository.java
  src/main/java/com/sooum/core/domain/card/service/FeedCardService.java
  src/main/java/com/sooum/core/domain/follow/controller/FollowController.java
  src/main/java/com/sooum/core/domain/follow/repository/FollowRepository.java
  src/main/java/com/sooum/core/domain/follow/service/FollowService.java
  src/main/java/com/sooum/core/domain/img/service/AWSImgService.java
  src/main/java/com/sooum/core/domain/img/service/ImgService.java
  src/main/java/com/sooum/core/domain/member/controller/ProfileController.java
  src/main/java/com/sooum/core/domain/member/dto/ProfileDto.java
  src/main/java/com/sooum/core/domain/member/entity/Member.java
  src/main/java/com/sooum/core/domain/member/repository/MemberRepository.java
  src/main/java/com/sooum/core/domain/member/service/MemberInfoService.java
  src/main/java/com/sooum/core/domain/member/service/MemberService.java
  src/main/java/com/sooum/core/domain/member/service/ProfileService.java
  src/main/java/com/sooum/core/domain/visitor/entity/Visitor.java
  src/main/java/com/sooum/core/domain/visitor/repository/VisitorRepository.java
  src/main/java/com/sooum/core/domain/visitor/service/VisitorService.java
Labels: 정우, feature

#145 Feat: favorite tags retrieval api
  src/main/java/com/sooum/core/domain/block/service/BlockMemberService.java
  src/main/java/com/sooum/core/domain/card/repository/FeedCardRepository.java
  src/main/java/com/sooum/core/domain/card/service/FeedCardService.java
  src/main/java/com/sooum/core/domain/tag/controller/TagController.java
  src/main/java/com/sooum/core/domain/tag/dto/TagDto.java
  src/main/java/com/sooum/core/domain/tag/repository/FavoriteTagRepository.java
  src/main/java/com/sooum/core/domain/tag/repository/FeedTagRepository.java
  src/main/java/com/sooum/core/domain/tag/service/FavoriteTagService.java
  src/main/java/com/sooum/core/domain/tag/service/TagService.java
  src/main/java/com/sooum/core/global/util/NextPageLinkGenerator.java
Labels: 지원, feature

#148 refactor: 팔로우 저장 & 수정 트랜잭션 전파 설정 변경
  src/main/java/com/sooum/core/domain/follow/service/FollowManagementService.java
  src/main/java/com/sooum/core/domain/follow/service/FollowService.java
Labels: 정우, refactor

#150 feat: 팔로워, 팔로잉와 계정 상태 조회 API 구현
  src/main/java/com/sooum/core/domain/follow/controller/FollowController.java
  src/main/java/com/sooum/core/domain/follow/dto/FollowDto.java
  src/main/java/com/sooum/core/domain/follow/dto/FollowInfoDto.java
  src/main/java/com/sooum/core/domain/follow/repository/FollowRepository.java
  src/main/java/com/sooum/core/domain/follow/service/FollowInfoService.java
  src/main/java/com/sooum/core/domain/follow/service/FollowService.java
  src/main/java/com/sooum/core/domain/member/controller/MemberSettingController.java
  src/main/java/com/sooum/core/domain/member/controller/ProfileController.java
  src/main/java/com/sooum/core/domain/member/dto/MemberDto.java
  src/main/java/com/sooum/core/domain/member/entity/Member.java
  src/main/java/com/sooum/core/domain/member/repository/MemberRepository.java
  src/main/java/com/sooum/core/domain/member/service/MemberService.java
  src/main/java/com/sooum/core/global/util/NextPageLinkGenerator.java
Labels: 호왕, feature

#161 feat: 공지 조회 api
  src/main/java/com/sooum/core/domain/notice/controller/NoticeController.java
  src/main/java/com/sooum/core/domain/notice/dto/NoticeDto.java
  src/main/java/com/sooum/core/domain/notice/entity/Notice.java
  src/main/java/com/sooum/core/domain/notice/repository/NoticeRepository.java
  src/main/java/com/sooum/core/domain/notice/service/NoticeService.java
Labels: 정우, feature

#154 Feat: get my comment cards
  src/main/java/com/sooum/core/domain/card/dto/MyCardDto.java
  src/main/java/com/sooum/core/domain/card/dto/MyCommentCardDto.java
  src/main/java/com/sooum/core/domain/card/repository/CommentCardRepository.java
  src/main/java/com/sooum/core/domain/card/service/CommentCardService.java
  src/main/java/com/sooum/core/domain/card/service/CommentInfoService.java
  src/main/java/com/sooum/core/domain/member/controller/MemberController.java
  src/main/java/com/sooum/core/global/util/NextPageLinkGenerator.java
  src/test/java/com/sooum/core/domain/card/repository/CommentCardRepositoryTest.java
  src/test/java/com/sooum/core/domain/card/service/CommentCardServiceTest.java
Labels: 지원, feature

#163 refactor: font_size 추가 및 태그 카운트 로직 수정
  src/main/java/com/sooum/core/domain/card/dto/CreateCommentDto.java
  src/main/java/com/sooum/core/domain/card/dto/CreateFeedCardDto.java
  src/main/java/com/sooum/core/domain/card/entity/fontsize/FontSize.java
  src/main/java/com/sooum/core/domain/card/service/FeedService.java
  src/main/java/com/sooum/core/domain/tag/entity/Tag.java
  src/main/java/com/sooum/core/domain/tag/repository/TagRepository.java
  src/main/java/com/sooum/core/domain/tag/service/TagService.java
Labels: 지원, refactor

#164 refactor: 최신 글 조회 쿼리 하나로 묶음
  src/main/java/com/sooum/core/domain/card/controller/LatestFeedController.java
  src/main/java/com/sooum/core/domain/card/repository/FeedCardRepository.java
  src/main/java/com/sooum/core/domain/card/service/FeedCardService.java
  src/main/java/com/sooum/core/domain/card/service/LatestFeedService.java
  src/main/java/com/sooum/core/domain/report/entity/reporttype/ReportType.java
Labels: 정우, refactor

#165 Feat/profile update and account transfer code
  src/main/java/com/sooum/core/domain/img/controller/ImgController.java
  src/main/java/com/sooum/core/domain/img/service/AWSImgService.java
  src/main/java/com/sooum/core/domain/img/service/ImgService.java
  src/main/java/com/sooum/core/domain/img/service/LocalImgService.java
  src/main/java/com/sooum/core/domain/member/controller/MemberSettingController.java
  src/main/java/com/sooum/core/domain/member/controller/ProfileController.java
  src/main/java/com/sooum/core/domain/member/dto/AccountTransferDto.java
  src/main/java/com/sooum/core/domain/member/dto/ProfileDto.java
  src/main/java/com/sooum/core/domain/member/entity/AccountTransfer.java
  src/main/java/com/sooum/core/domain/member/entity/Member.java
  src/main/java/com/sooum/core/domain/member/entity/TransferId.java
  src/main/java/com/sooum/core/domain/member/repository/AccountTransferRepository.java
  src/main/java/com/sooum/core/domain/member/repository/TransferIdRepository.java
  src/main/java/com/sooum/core/domain/member/service/AccountTransferService.java
  src/main/java/com/sooum/core/domain/member/service/ProfileService.java
  src/main/java/com/sooum/core/domain/member/service/TransferIdService.java
  src/main/java/com/sooum/core/global/config/security/SecurityConfig.java
  src/main/java/com/sooum/core/global/exceptionmessage/ExceptionMessage.java
Labels: 호왕, feature

#167 refactor: 불필요한 어노테이션 제거
  src/main/java/com/sooum/core/domain/card/service/FeedService.java
Labels: 지원

#169 refactor: 카드 삭제 상태로만 변경하도록 로직 변경
  src/main/java/com/sooum/core/domain/card/entity/Card.java
  src/main/java/com/sooum/core/domain/card/repository/CommentCardRepository.java
  src/main/java/com/sooum/core/domain/card/service/CommentCardService.java
  src/main/java/com/sooum/core/domain/card/service/FeedService.java
  src/main/java/com/sooum/core/domain/card/service/LatestFeedService.java
  src/main/java/com/sooum/core/domain/img/repository/ImgRepository.java
  src/main/java/com/sooum/core/domain/img/service/UserImgService.java
  src/main/java/com/sooum/core/domain/member/controller/MemberSettingController.java
  src/main/java/com/sooum/core/domain/member/controller/ProfileController.java
  src/main/java/com/sooum/core/domain/member/entity/AccountTransfer.java
  src/main/java/com/sooum/core/domain/member/service/AccountTransferService.java
  src/main/java/com/sooum/core/domain/member/service/ProfileService.java
  src/main/java/com/sooum/core/domain/notice/controller/NoticeController.java
  src/main/java/com/sooum/core/domain/report/repository/CommentReportRepository.java
  src/main/java/com/sooum/core/domain/report/repository/FeedReportRepository.java
  src/main/java/com/sooum/core/domain/report/service/CommentReportService.java
  src/main/java/com/sooum/core/domain/report/service/FeedReportService.java
  src/main/java/com/sooum/core/domain/tag/repository/CommentTagRepository.java
  src/main/java/com/sooum/core/domain/tag/repository/FeedTagRepository.java
  src/main/java/com/sooum/core/domain/tag/service/FavoriteTagService.java
Labels: 정우, refactor

#170 test: 팔로우, 팔로워 조회, 계정이관 및 프로필 수정 API 테스트
  src/main/java/com/sooum/core/domain/member/repository/AccountTransferRepository.java
  src/main/java/com/sooum/core/domain/member/service/AccountTransferService.java
  src/test/java/com/sooum/core/domain/card/service/CardServiceTest.java
  src/test/java/com/sooum/core/domain/follow/repository/FollowRepositoryTest.java
  src/test/java/com/sooum/core/domain/member/service/AccountTransferServiceTest.java
  src/test/java/com/sooum/core/domain/member/service/ProfileServiceTest.java
Labels: 호왕, test

#172 refactor: 홈피드거리순조회 쿼리수정 및 역직렬화 문제해결
  src/main/java/com/sooum/core/domain/card/controller/DistanceCardController.java
  src/main/java/com/sooum/core/domain/card/dto/CreateCardDto.java
  src/main/java/com/sooum/core/domain/card/dto/CreateCommentDto.java
  src/main/java/com/sooum/core/domain/card/dto/CreateFeedCardDto.java
  src/main/java/com/sooum/core/domain/card/repository/FeedCardRepository.java
  src/main/java/com/sooum/core/domain/card/service/DistanceFeedService.java
  src/main/java/com/sooum/core/domain/card/service/FeedCardService.java
Labels: 지원, refactor

#174 fix: 이전카드 삭제시 이미지 발급 안하도록 수정
  src/main/java/com/sooum/core/domain/card/service/DetailFeedService.java
Labels: fix, 지원

#182 Refactor/separate sign up process
  src/main/java/com/sooum/core/domain/member/controller/MemberAuthController.java
  src/main/java/com/sooum/core/domain/member/dto/AuthDTO.java
  src/main/java/com/sooum/core/domain/member/service/MemberInfoService.java
Labels: 경규, refactor

#187 notice:공지글 조회 쿼리 정렬 조건 추가
  src/main/java/com/sooum/core/domain/card/dto/CreateFeedCardDto.java
  src/main/java/com/sooum/core/domain/notice/repository/NoticeRepository.java
  src/test/java/com/sooum/core/domain/card/service/CommentLikeServiceTest.java
Labels: 정우, refactor

#188 fix: update untilBan
  src/main/java/com/sooum/core/domain/member/entity/Member.java
Labels: fix, 경규

#157 Feat: find my card list api
  src/main/java/com/sooum/core/domain/card/controller/CardController.java
  src/main/java/com/sooum/core/domain/card/dto/MyFeedCardDto.java
  src/main/java/com/sooum/core/domain/card/repository/FeedCardRepository.java
  src/main/java/com/sooum/core/domain/card/service/CardService.java
  src/main/java/com/sooum/core/domain/card/service/CommentLikeService.java
  src/main/java/com/sooum/core/domain/card/service/FeedCardService.java
  src/main/java/com/sooum/core/domain/card/service/FeedLikeService.java
  src/main/java/com/sooum/core/domain/member/controller/MemberController.java
  src/main/java/com/sooum/core/global/util/NextPageLinkGenerator.java
Labels: 경규, feature
