Repository prj154654168/Sooum-BE, pull requests merged in 2024-12, with the labels that each got.

#253 카드 삭제 시 인기글 삭제 로직 추가
  boot/external-api/src/main/java/com/sooum/api/card/service/FeedService.java
Labels: 정우, refactor

#255 팔로잉 정보 추가'
  boot/external-api/src/main/java/com/sooum/api/member/dto/ProfileDto.java
  boot/external-api/src/main/java/com/sooum/api/member/service/ProfileService.java
Labels: 정우, refactor

#262 refactor: 자신의 피드 카드만 조회하는 API에서 상대방 피드카드도 조회하는 API로 수정
  boot/external-api/src/main/java/com/sooum/api/member/controller/MemberController.java
Labels: 호왕, refactor

#266 refactor: 팔로워/팔로잉 조회 API에서 본인인 경우 추가
  boot/external-api/src/main/java/com/sooum/api/member/controller/ProfileController.java
Labels: 호왕, refactor

#274 Refactor/popular feed retrieve
  boot/batch/src/main/java/com/sooum/batch/card/batch/repository/PopularCardBatchRepository.java
  boot/external-api/src/main/java/com/sooum/api/card/service/PopularRetrieveService.java
  boot/external-api/src/main/java/com/sooum/api/notice/controller/NoticeController.java
  data/core-data/src/main/java/com/sooum/data/card/entity/FeedCard.java
  data/core-data/src/main/java/com/sooum/data/card/repository/PopularFeedRepository.java
  data/core-data/src/main/java/com/sooum/data/card/service/PopularFeedService.java
Labels: 호왕, refactor

#276 Refactor/member feed and comment retrieve
  boot/batch/src/main/java/com/sooum/batch/card/batch/repository/PopularCardBatchRepository.java
  boot/external-api/src/main/java/com/sooum/api/card/service/CardService.java
  boot/external-api/src/main/java/com/sooum/api/card/service/FeedCardUseCase.java
  boot/external-api/src/main/java/com/sooum/api/member/controller/MemberController.java
  data/core-data/src/main/java/com/sooum/data/card/repository/FeedCardRepository.java
  data/core-data/src/main/java/com/sooum/data/card/repository/PopularFeedRepository.java
  data/core-data/src/main/java/com/sooum/data/card/service/FeedCardService.java
  data/core-data/src/main/java/com/sooum/data/card/service/PopularFeedService.java
  data/core-data/src/main/java/com/sooum/data/suspended/repository/SuspendedRepository.java
  data/core-data/src/main/java/com/sooum/data/tag/repository/CachedTagRepository.java
  data/core-data/src/main/java/com/sooum/data/tag/repository/TagRepository.java
Labels: 호왕, refactor

#279 tag 개수 조회 수정
  boot/external-api/src/main/java/com/sooum/api/notice/dto/NoticeDto.java
  boot/external-api/src/main/java/com/sooum/api/tag/service/TagUseCase.java
  data/core-data/src/main/java/com/sooum/data/notice/entity/Notice.java
  data/core-data/src/main/java/com/sooum/data/notice/entity/noticetype/NoticeType.java
Labels: 정우, refactor

#280 refactor: transactional scope modify
  boot/external-api/src/main/java/com/sooum/api/tag/service/FavoriteTagUseCase.java
Labels: 지원, refactor

#285 feat/rsa-key-scheduler
  boot/external-api/build.gradle
  boot/external-api/src/main/java/com/sooum/ExternalApiApplication.java
  boot/external-api/src/main/java/com/sooum/api/member/service/BlackListUseCase.java
  boot/external-api/src/main/java/com/sooum/api/rsa/service/RsaUseCase.java
  boot/external-api/src/main/java/com/sooum/global/aop/aspect/SlackAspect.java
  boot/external-api/src/main/java/com/sooum/global/config/redis/RedisConfig.java
  boot/external-api/src/main/java/com/sooum/global/rsa/RsaProvider.java
  boot/external-api/src/main/java/com/sooum/global/rsa/RsaScheduler.java
  boot/external-api/src/main/java/com/sooum/global/rsa/service/RsaSchedulerService.java
  data/core-data/src/main/java/com/sooum/data/rsa/repository/RsaRepository.java
  data/core-data/src/main/java/com/sooum/data/rsa/service/RsaService.java
Labels: fix, 정우, feature

#293 fix: timeZone 관련 query 수정
  boot/batch/src/main/java/com/sooum/batch/card/batch/repository/CommentCardBatchRepository.java
  boot/batch/src/main/java/com/sooum/batch/card/batch/repository/FeedLikeBatchRepository.java
  boot/batch/src/main/java/com/sooum/batch/card/batch/service/SavePopularCardService.java
  data/core-data/src/main/java/com/sooum/data/card/repository/FeedCardRepository.java
  data/core-data/src/main/java/com/sooum/data/card/service/FeedCardService.java
Labels: fix, 호왕, 정우, 지원

#295 답카드 삭제 쿼리 타입 오류 수정
  data/core-data/src/main/java/com/sooum/data/report/repository/CommentReportRepository.java
Labels: fix, 정우

#298 redis repository disable
  boot/external-api/src/main/resources/application.yml
Labels: fix, 정우

#301 refactor: 신고하기 API request data를 queryString -> body로 변경
  boot/external-api/src/main/java/com/sooum/api/report/controller/ReportController.java
  boot/external-api/src/main/java/com/sooum/api/report/dto/ReportDto.java
Labels: 호왕, refactor

#303 댓글 작성여부 판별 메서드 수정
  boot/external-api/src/main/java/com/sooum/api/card/service/CommentInfoService.java
  boot/external-api/src/main/java/com/sooum/api/card/service/DistanceFeedService.java
  boot/external-api/src/main/java/com/sooum/api/card/service/FeedService.java
  boot/external-api/src/main/java/com/sooum/api/card/service/LatestFeedUseCase.java
  boot/external-api/src/main/java/com/sooum/api/card/service/PopularRetrieveService.java
  boot/external-api/src/main/java/com/sooum/api/card/service/TagFeedInfoService.java
Labels: fix, 정우

#305 code error 수정
  boot/external-api/src/main/java/com/sooum/api/member/controller/MemberAuthController.java
  boot/external-api/src/main/java/com/sooum/global/config/jwt/JwtAuthenticationFilter.java
Labels: fix, 정우

#307 filter의 url별 http Method 구분을 위해 map으로 변경
  boot/external-api/src/main/java/com/sooum/global/config/jwt/JwtAuthenticationFilter.java
Labels: fix, 정우

#310 refactor: jsonProperty에 따른 final 삭제
  boot/external-api/src/main/java/com/sooum/api/follow/dto/FollowInfoDto.java
Labels: 호왕, refactor

#315 refacotr: @Modifying에 @Transactional 추가
  boot/batch/src/main/java/com/sooum/batch/card/batch/repository/PopularCardBatchRepository.java
  data/core-data/src/main/java/com/sooum/data/block/repository/BlockRepository.java
  data/core-data/src/main/java/com/sooum/data/card/repository/CommentCardRepository.java
  data/core-data/src/main/java/com/sooum/data/card/repository/CommentLikeRepository.java
  data/core-data/src/main/java/com/sooum/data/card/repository/FeedCardRepository.java
  data/core-data/src/main/java/com/sooum/data/card/repository/FeedLikeRepository.java
  data/core-data/src/main/java/com/sooum/data/card/repository/PopularFeedRepository.java
  data/core-data/src/main/java/com/sooum/data/follow/repository/FollowRepository.java
  data/core-data/src/main/java/com/sooum/data/img/repository/CardImgRepository.java
  data/core-data/src/main/java/com/sooum/data/img/repository/ProfileImgRepository.java
  data/core-data/src/main/java/com/sooum/data/member/repository/AccountTransferRepository.java
  data/core-data/src/main/java/com/sooum/data/member/repository/MemberRepository.java
  data/core-data/src/main/java/com/sooum/data/member/repository/PolicyTermRepository.java
  data/core-data/src/main/java/com/sooum/data/member/repository/RefreshTokenRepository.java
  data/core-data/src/main/java/com/sooum/data/report/repository/CommentReportRepository.java
  data/core-data/src/main/java/com/sooum/data/report/repository/FeedReportRepository.java
  data/core-data/src/main/java/com/sooum/data/rsa/repository/RsaRepository.java
  data/core-data/src/main/java/com/sooum/data/tag/repository/CommentTagRepository.java
  data/core-data/src/main/java/com/sooum/data/tag/repository/FavoriteTagRepository.java
  data/core-data/src/main/java/com/sooum/data/tag/repository/FeedTagRepository.java
  data/core-data/src/main/java/com/sooum/data/tag/repository/TagRepository.java
  data/core-data/src/main/java/com/sooum/data/visitor/repository/VisitorRepository.java
Labels: 호왕, 정우, 지원, refactor

#317 feat/notification-retrieve-API
  boot/external-api/src/main/java/com/sooum/api/appversion/controller/AppVersionController.java
  boot/external-api/src/main/java/com/sooum/api/card/service/FeedService.java
  boot/external-api/src/main/java/com/sooum/api/notification/controller/NotificationController.java
  boot/external-api/src/main/java/com/sooum/api/notification/dto/NotificationDto.java
  boot/external-api/src/main/java/com/sooum/api/notification/service/NotificationUseCase.java
  boot/external-api/src/main/java/com/sooum/global/config/jwt/JwtAuthenticationFilter.java
  boot/external-api/src/main/java/com/sooum/global/config/security/SecurityConfig.java
  data/core-data/src/main/java/com/sooum/data/app/entity/AppVersion.java
  data/core-data/src/main/java/com/sooum/data/app/repository/AppVersionRepository.java
  data/core-data/src/main/java/com/sooum/data/card/repository/FeedCardRepository.java
  data/core-data/src/main/java/com/sooum/data/card/service/FeedCardService.java
  data/core-data/src/main/java/com/sooum/data/notification/entity/NotificationHistory.java
  data/core-data/src/main/java/com/sooum/data/notification/repository/NotificationHistoryRepository.java
  data/core-data/src/main/java/com/sooum/data/notification/service/NotificationHistoryService.java
Labels: 정우, feature

#319 refactor:favorite-tag-feed-card-sorting
  data/core-data/src/main/java/com/sooum/data/tag/repository/FeedTagRepository.java
Labels: 지원, refactor

#320 fix: 만료된 토큰도 에러없이 blacklist에 추가하도록 수정
  boot/external-api/src/main/java/com/sooum/api/member/service/MemberWithdrawalService.java
  boot/external-api/src/main/java/com/sooum/global/config/jwt/TokenProvider.java
Labels: fix, 지원

#323 fix/ban restriction code
  boot/external-api/src/main/java/com/sooum/api/card/service/FeedService.java
  boot/external-api/src/main/java/com/sooum/api/member/exception/BannedUserException.java
  boot/external-api/src/main/java/com/sooum/global/exceptionhandler/ValidExceptionHandler.java
  boot/external-api/src/main/java/com/sooum/global/exceptionmessage/ExceptionMessage.java
Labels: 지원, refactor

#322 Feat/notificationAndUpdateFCMToken
  boot/batch/src/main/java/com/sooum/batch/card/batch/repository/CommentCardBatchRepository.java
  boot/batch/src/main/java/com/sooum/batch/card/batch/repository/FeedLikeBatchRepository.java
  boot/batch/src/main/java/com/sooum/batch/card/batch/service/SavePopularCardService.java
  boot/batch/src/main/java/com/sooum/batch/img/service/ImgService.java
  boot/external-api/build.gradle
  boot/external-api/src/main/java/com/sooum/ExternalApiApplication.java
  boot/external-api/src/main/java/com/sooum/api/card/controller/FeedCardController.java
  boot/external-api/src/main/java/com/sooum/api/card/service/CardLikeService.java
  boot/external-api/src/main/java/com/sooum/api/card/service/CardService.java
  boot/external-api/src/main/java/com/sooum/api/card/service/FeedService.java
  boot/external-api/src/main/java/com/sooum/api/img/service/AWSImgService.java
  boot/external-api/src/main/java/com/sooum/api/img/service/LocalImgService.java
  boot/external-api/src/main/java/com/sooum/api/member/controller/MemberController.java
  boot/external-api/src/main/java/com/sooum/api/member/dto/MemberDto.java
  boot/external-api/src/main/java/com/sooum/api/member/service/MemberUseCase.java
  boot/external-api/src/main/java/com/sooum/api/member/service/ProfileService.java
  boot/external-api/src/main/java/com/sooum/api/notification/dto/FCMDto.java
  boot/external-api/src/main/java/com/sooum/api/notification/event/FCMEventListener.java
  boot/external-api/src/main/java/com/sooum/api/notification/exception/FcmServerException.java
  boot/external-api/src/main/java/com/sooum/api/notification/service/FCMMsgGenerator.java
  boot/external-api/src/main/java/com/sooum/api/notification/service/FCMSender.java
  boot/external-api/src/main/java/com/sooum/api/notification/service/NotificationUseCase.java
  boot/external-api/src/main/java/com/sooum/api/notification/service/SendFCMService.java
  boot/external-api/src/main/java/com/sooum/api/report/controller/ReportController.java
  boot/external-api/src/main/java/com/sooum/api/report/service/CommentReportUseCase.java
  boot/external-api/src/main/java/com/sooum/api/report/service/FeedReportUseCase.java
  boot/external-api/src/main/java/com/sooum/api/report/service/ReportService.java
  boot/external-api/src/main/java/com/sooum/api/suspended/controller/SuspendedController.java
  boot/external-api/src/main/java/com/sooum/global/aop/aspect/SlackAspect.java
  boot/external-api/src/main/java/com/sooum/global/config/fcm/FcmConfig.java
  boot/external-api/src/main/java/com/sooum/global/config/redis/RedisConfig.java
  boot/external-api/src/main/java/com/sooum/global/slack/service/SlackService.java
  boot/external-api/src/main/resources/application.yml
  cloud/src/main/java/com/sooum/client/aws/rekognition/RekognitionService.java
  cloud/src/main/java/com/sooum/client/aws/s3/S3FCMService.java
  cloud/src/main/java/com/sooum/client/aws/s3/S3ImgService.java
  cloud/src/main/resources/application-cloud.yml
  data/core-data/src/main/java/com/sooum/data/card/entity/Card.java
  data/core-data/src/main/java/com/sooum/data/card/repository/CommentLikeRepository.java
  data/core-data/src/main/java/com/sooum/data/card/service/CommentCardService.java
  data/core-data/src/main/java/com/sooum/data/card/service/CommentLikeService.java
  data/core-data/src/main/java/com/sooum/data/card/service/FeedCardService.java
  data/core-data/src/main/java/com/sooum/data/card/service/FeedLikeService.java
  data/core-data/src/main/java/com/sooum/data/member/entity/Member.java
  data/core-data/src/main/java/com/sooum/data/notification/entity/NotificationHistory.java
  data/core-data/src/main/java/com/sooum/data/notification/entity/notificationtype/NotificationType.java
  data/core-data/src/main/java/com/sooum/data/notification/repository/NotificationHistoryRepository.java
  data/core-data/src/main/java/com/sooum/data/notification/service/NotificationHistoryService.java
  data/core-data/src/main/java/com/sooum/data/report/service/CommentReportService.java
  data/core-data/src/main/java/com/sooum/data/report/service/FeedReportService.java
  data/core-data/src/main/java/com/sooum/data/rsa/service/RsaService.java
  data/core-data/src/main/java/com/sooum/data/tag/repository/TagRepository.java
  data/core-data/src/main/java/com/sooum/data/tag/service/TagService.java
Labels: 호왕, feature

#324 refactor: profile update 메소드에서 profileImg의 profileOnwer update하는 로직 추가
  boot/external-api/src/main/java/com/sooum/api/member/service/ProfileService.java
  data/core-data/src/main/java/com/sooum/data/img/entity/ProfileImg.java
  data/core-data/src/main/java/com/sooum/data/img/repository/ProfileImgRepository.java
  data/core-data/src/main/java/com/sooum/data/img/service/ProfileImgService.java
Labels: 호왕, refactor

#325 Feat suspended batch
  boot/batch/src/main/java/com/sooum/batch/member/SuspendedDeleteScheduler.java
  boot/batch/src/main/java/com/sooum/batch/member/repository/SuspendedBatchRepository.java
  boot/batch/src/main/java/com/sooum/batch/member/service/DeleteSuspensionService.java
Labels: 지원, feature

#327 Feat blacklist batch
  boot/batch/src/main/java/com/sooum/batch/blacklist/BlacklistDeleteBatchConfig.java
  boot/batch/src/main/java/com/sooum/batch/blacklist/repository/BlacklistBatchRepository.java
  boot/batch/src/main/java/com/sooum/batch/member/BlacklistFetchConfig.java
  boot/batch/src/main/java/com/sooum/batch/suspended/SuspendedDeleteScheduler.java
  boot/batch/src/main/java/com/sooum/batch/suspended/repository/SuspendedBatchRepository.java
  boot/batch/src/main/java/com/sooum/batch/suspended/service/DeleteSuspensionService.java
  data/core-data/src/main/java/com/sooum/data/member/repository/BlacklistRepository.java
Labels: 지원, feature

#330 feat: 알림 허용 유무 관련 API 구현
  boot/external-api/src/main/java/com/sooum/api/card/service/CardLikeService.java
  boot/external-api/src/main/java/com/sooum/api/card/service/FeedService.java
  boot/external-api/src/main/java/com/sooum/api/member/controller/MemberController.java
  boot/external-api/src/main/java/com/sooum/api/member/dto/MemberDto.java
  boot/external-api/src/main/java/com/sooum/api/member/service/MemberUseCase.java
  boot/external-api/src/main/java/com/sooum/api/report/service/CommentReportUseCase.java
  boot/external-api/src/main/java/com/sooum/api/report/service/FeedReportUseCase.java
  data/core-data/src/main/java/com/sooum/data/member/entity/Member.java
  data/core-data/src/main/java/com/sooum/data/member/repository/MemberRepository.java
  data/core-data/src/main/java/com/sooum/data/member/service/MemberService.java
Labels: 호왕, feature

#332 feat: add redis blacklist
  boot/external-api/src/main/java/com/sooum/api/member/service/MemberWithdrawalService.java
Labels: 지원, feature

#333 인증이 필요한 api 호출을 1초 이내에 한번 이상 못하도록 변경
  boot/external-api/src/main/java/com/sooum/ExternalApiApplication.java
  boot/external-api/src/main/java/com/sooum/global/config/mvc/WebMvcConfig.java
  boot/external-api/src/main/java/com/sooum/global/config/ratelimiter/RateLimitInterceptor.java
  boot/external-api/src/main/java/com/sooum/global/config/ratelimiter/RequestRateLimiter.java
  boot/external-api/src/main/java/com/sooum/global/config/redis/RedisConfig.java
  boot/external-api/src/main/java/com/sooum/global/config/security/path/ExcludeAuthPathProperties.java
  boot/external-api/src/main/resources/application.yml
Labels: 정우, feature

#335 ant matcher -> pathPattern으로 변경 및 하나의 설정 파일에서 인증 필요없는 경로 통합 관리
  boot/external-api/src/main/java/com/sooum/api/member/controller/ProfileController.java
  boot/external-api/src/main/java/com/sooum/global/config/jwt/JwtAuthenticationFilter.java
  boot/external-api/src/main/java/com/sooum/global/config/ratelimiter/RateLimitInterceptor.java
  boot/external-api/src/main/java/com/sooum/global/config/ratelimiter/RequestRateLimiter.java
  boot/external-api/src/main/java/com/sooum/global/config/security/SecurityConfig.java
  boot/external-api/src/main/resources/application.yml
Labels: 정우, refactor

#337 refactor: 팔로잉, 팔로워 조회 시 요청자 본인인지 확인 데이터 추가
  boot/external-api/src/main/java/com/sooum/api/follow/dto/FollowDto.java
  boot/external-api/src/main/java/com/sooum/api/follow/dto/FollowInfoDto.java
  boot/external-api/src/main/java/com/sooum/api/follow/service/FollowInfoService.java
Labels: 호왕, refactor

#339 refactor: 댓글 카드 알림 저장 시 targetCardPk를 댓글 카드로 변경
  boot/external-api/src/main/java/com/sooum/api/card/service/FeedService.java
  boot/external-api/src/main/java/com/sooum/api/notification/service/NotificationUseCase.java
  data/core-data/src/main/java/com/sooum/data/notification/entity/NotificationHistory.java
Labels: 호왕, refactor

#343 refactor: code deploy trigger 추가
  .github/workflows/deploy.yml
Labels: 호왕, refactor

#344 refactor: git action credential 위치 변경
  .github/workflows/deploy.yml
Labels: 호왕, refactor

#345 refactor: git action credential 변경
  .github/workflows/deploy.yml
Labels: 호왕, refactor

#346 fix: bug fix
  .github/workflows/deploy.yml
Labels: fix, 호왕

#348 refactor: 누락된 exclude api path 추가
  boot/external-api/src/main/resources/application.yml
Labels: 호왕, refactor
