Repository prj154654168/Sooum-BE, pull requests merged in 2025-02, with the labels that each got.

#437 Feat/account transfer fcm
  boot/external-api/src/main/java/com/sooum/api/member/service/AccountTransferUseCase.java
  boot/external-api/src/main/java/com/sooum/api/notification/event/FCMEventListener.java
  boot/external-api/src/main/java/com/sooum/api/notification/service/SendFCMService.java
  boot/external-api/src/main/java/com/sooum/global/slack/service/SlackService.java
  data/core-data/src/main/java/com/sooum/data/notification/entity/notificationtype/NotificationType.java
Labels: fix, 호왕

#438 refactor: 계정 이관시 보내는 알림 멘트 추가
  boot/external-api/src/main/java/com/sooum/api/notification/service/FCMMsgGenerator.java
Labels: 호왕, refactor

#439 refactor: system 알림일 경우 targetCardId에 null을 string null로 변경
  boot/external-api/src/main/java/com/sooum/api/notification/service/FCMMsgGenerator.java
Labels: 호왕, refactor

#441 위도 또는 경도가 0이면 포인트 null을 저장
  boot/external-api/src/main/java/com/sooum/api/card/dto/CreateCardDto.java
  boot/external-api/src/main/java/com/sooum/api/card/dto/CreateCommentDto.java
  boot/external-api/src/main/java/com/sooum/api/card/dto/CreateFeedCardDto.java
Labels: fix, 호왕, 정우

#443 Rsa key가 업데이트 되지 않아도 가장 마지막 키를 반환하고 slack을 전송하도록 이벤트 리스너 구현
  boot/batch/src/main/java/com/sooum/batch/rsa/RsaKeyGenerateConfig.java
  boot/batch/src/main/java/com/sooum/batch/rsa/service/RsaBatchService.java
  boot/external-api/src/main/java/com/sooum/api/rsa/service/RsaUseCase.java
  boot/external-api/src/main/java/com/sooum/global/slack/service/SlackService.java
  data/core-data/src/main/java/com/sooum/data/common/event/SlackEvent.java
  data/core-data/src/main/java/com/sooum/data/rsa/repository/RsaRepository.java
  data/core-data/src/main/java/com/sooum/data/rsa/service/RsaService.java
Labels: fix, 정우

#447 test/test-config
  boot/external-api/build.gradle
  boot/external-api/src/docs/asciidoc/api/member/auth/Auth.adoc
  boot/external-api/src/docs/asciidoc/api/member/profile/Profile.adoc
  boot/external-api/src/docs/asciidoc/index.adoc
  boot/external-api/src/main/resources/application.yml
  boot/external-api/src/test/java/com/sooum/api/IntegrationTestSupport.java
  boot/external-api/src/test/java/com/sooum/api/docs/RestDocsSupport.java
  boot/external-api/src/test/java/com/sooum/api/docs/member/MemberAuthControllerDocs.java
  boot/external-api/src/test/java/com/sooum/api/docs/member/ProfileControllerDocs.java
  boot/external-api/src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  boot/external-api/src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
  build.gradle
Labels: 정우, test

#449 refactor: FCM iOS 백그라운드 처리를 위한 Content-Available 필드 추가
  boot/external-api/src/main/java/com/sooum/api/notification/service/FCMMsgGenerator.java
Labels: 호왕, refactor

#451 block docs
  boot/external-api/src/docs/asciidoc/api/block/Block.adoc
  boot/external-api/src/docs/asciidoc/index.adoc
  boot/external-api/src/test/java/com/sooum/api/docs/block/BlockControllerDocs.java
Labels: 정우, test

#453 refactor: build할 때 -x test 제거
  .github/workflows/deploy.yml
Labels: 호왕, 정우, refactor

#459 test/latest-feed-query
  boot/external-api/build.gradle
  boot/external-api/src/test/java/com/sooum/api/IntegrationTestSupport.java
  boot/external-api/src/test/java/com/sooum/api/card/service/LatestFeedUseCaseTest.java
  boot/external-api/src/test/java/com/sooum/data/DataJpaTestSupport.java
  boot/external-api/src/test/java/com/sooum/data/block/repository/BlockRepositoryTest.java
  boot/external-api/src/test/java/com/sooum/data/card/repository/CommentCardRepositoryTest.java
  boot/external-api/src/test/java/com/sooum/data/card/repository/FeedCardRepositoryTest.java
  boot/external-api/src/test/java/com/sooum/data/card/repository/FeedLikeRepositoryTest.java
  boot/external-api/src/test/java/com/sooum/docs/RestDocsSupport.java
  boot/external-api/src/test/java/com/sooum/docs/block/BlockControllerDocs.java
  boot/external-api/src/test/java/com/sooum/docs/member/MemberAuthControllerDocs.java
  boot/external-api/src/test/java/com/sooum/docs/member/ProfileControllerDocs.java
  boot/external-api/src/test/resources/application.yml
  build.gradle
Labels: 정우, test

#462 test/rsa-key-service
  boot/batch/src/main/java/com/sooum/batch/rsa/RsaScheduler.java
  boot/batch/src/main/java/com/sooum/batch/rsa/service/RsaSchedulerService.java
  boot/batch/src/main/java/com/sooum/batch/tag/TagCacheConfig.java
  boot/batch/src/test/java/com/sooum/batch/IntegrationTestSupport.java
  boot/batch/src/test/resources/application.yml
  boot/external-api/src/main/java/com/sooum/ExternalApiApplication.java
  boot/external-api/src/main/java/com/sooum/api/member/service/BlackListUseCase.java
  boot/external-api/src/main/java/com/sooum/api/member/service/MemberWithdrawalService.java
  boot/external-api/src/main/java/com/sooum/api/rsa/service/RsaUseCase.java
  boot/external-api/src/main/java/com/sooum/global/config/redis/RedisConfig.java
  boot/external-api/src/test/java/com/sooum/api/IntegrationTestSupport.java
  boot/external-api/src/test/resources/application.yml
  build.gradle
Labels: 정우, test

#469 feat/rejoin-immediately-after-withdrawal
  boot/external-api/src/main/java/com/sooum/api/member/controller/MemberController.java
  boot/external-api/src/main/java/com/sooum/api/suspended/service/SuspendedUseCase.java
  boot/external-api/src/main/resources/application.yml
  data/core-data/src/main/java/com/sooum/data/suspended/repository/SuspendedRepository.java
  data/core-data/src/main/java/com/sooum/data/suspended/service/SuspendedService.java
Labels: 지원, feature

#471 refactor: 닉네임 최대 길이 8 -> 16
  boot/external-api/src/main/java/com/sooum/api/member/dto/ProfileDto.java
Labels: 호왕, refactor

#474 feat/version-api-v2
  boot/external-api/src/main/java/com/sooum/api/appversion/controller/AppVersionController.java
  boot/external-api/src/main/java/com/sooum/api/appversion/dto/AppVersionStatus.java
  boot/external-api/src/main/java/com/sooum/api/appversion/service/AppVersionService.java
  boot/external-api/src/test/java/com/sooum/api/appversion/service/AppVersionServiceTest.java
  boot/external-api/src/test/java/com/sooum/api/card/service/LatestFeedUseCaseTest.java
  data/core-data/src/main/java/com/sooum/data/app/entity/AppVersion.java
  data/core-data/src/main/java/com/sooum/data/app/repository/AppVersionRepository.java
Labels: 호왕, 정우, feature

#478 report 밴 횟수 증가 테스트
  boot/external-api/src/test/java/com/sooum/api/report/service/FeedReportUseCaseTest.java
Labels: 정우, test
