Repository prj154654168/Sooum-BE, pull requests merged in 2025-03, with the labels that each got.

#483 chunk size 100으로 수정 및 21시로 시간 변경
  boot/batch/src/main/java/com/sooum/batch/fcm/batch/SendFcmBatch.java
Labels: 정우, refactor

#489 fix: deviceId 암호화없이 request 받도록 수정
  boot/external-api/src/main/java/com/sooum/api/member/dto/MemberDto.java
  boot/external-api/src/main/java/com/sooum/api/suspended/service/SuspendedUseCase.java
Labels: fix, 지원

#490 refactor/app-version-v2
  boot/external-api/src/test/java/com/sooum/api/appversion/service/AppVersionServiceTest.java
Labels: 정우, test
