Repository prj154654168/Sooum-BE, pull requests merged in 2025-01, with the labels that each got.

#350 rsa 스캐줄러 코드 배치 모듈로 이동 및 git action 코드 수정
  .github/workflows/deploy.yml
  boot/batch/src/main/java/com/sooum/batch/rsa/RsaScheduler.java
  boot/batch/src/main/java/com/sooum/batch/rsa/service/RsaSchedulerService.java
  boot/external-api/src/main/java/com/sooum/ExternalApiApplication.java
Labels: 정우, refactor

#351 refactor/rsa-scheduler-batch
  .github/workflows/deploy.yml
Labels: fix, 정우

#352 refactor/rsa-scheduler-batch
  boot/batch/src/main/java/com/sooum/batch/blacklist/BlacklistDeleteBatchConfig.java
  boot/external-api/src/main/java/com/sooum/api/card/service/FeedService.java
  boot/external-api/src/main/java/com/sooum/api/follow/dto/FollowInfoDto.java
  boot/external-api/src/main/java/com/sooum/api/notification/service/FCMMsgGenerator.java
  boot/external-api/src/main/java/com/sooum/global/config/security/SecurityConfig.java
Labels: 정우, refactor

#354 refactor: 인기 있는 글 저장할 때 댓글 조건 변경
  boot/batch/src/main/java/com/sooum/batch/card/batch/repository/CommentCardBatchRepository.java
Labels: 호왕, refactor

#357 펑 피드카드의 커멘트카드에 태그가 잘못 들어간 예외 데이터도 삭제할 수 있도록 수정
  boot/batch/src/main/java/com/sooum/batch/card/batch/StoryDeleteBatchConfig.java
  boot/batch/src/main/java/com/sooum/batch/card/batch/dto/CommentRelatedEntitiesDeletionDto.java
  boot/batch/src/main/java/com/sooum/batch/card/batch/repository/CardImgBatchRepository.java
  boot/batch/src/main/java/com/sooum/batch/card/batch/repository/CommentCardBatchRepository.java
  boot/batch/src/main/java/com/sooum/batch/card/batch/repository/CommentTagBatchRepository.java
  boot/batch/src/main/java/com/sooum/batch/card/batch/repository/NotificationBatchRepository.java
Labels: fix, 정우

#360 알림 읽은 시간 추가 및 해 당 시간으로 읽은 알림 24시간 제한 조회 설정
  data/core-data/src/main/java/com/sooum/data/notification/entity/NotificationHistory.java
  data/core-data/src/main/java/com/sooum/data/notification/repository/NotificationHistoryRepository.java
  data/core-data/src/main/java/com/sooum/data/notification/service/NotificationHistoryService.java
Labels: 정우, refactor

#362 warmer
  boot/external-api/src/main/java/com/sooum/global/config/warmer/ApplicationWarmer.java
Labels: 호왕, 정우, feature

#370 refactor: git action branch main -> production 변경
  .github/workflows/deploy.yml
Labels: 호왕, refactor

#374 fix: default card @value 값 변경
  cloud/src/main/java/com/sooum/client/aws/s3/imgproperties/S3ImgPathProperties.java
Labels: fix, 호왕

#376 rate limit 1초에서 0.5초로 변경
  boot/external-api/src/main/java/com/sooum/global/config/ratelimiter/RequestRateLimiter.java
Labels: 정우, refactor

#378 Refactor/android fcm data
  boot/external-api/src/main/java/com/sooum/api/notification/service/FCMMsgGenerator.java
Labels: 호왕, refactor

#380 태그 개수 커멘트일 때 안올리도록 변경
  boot/external-api/src/main/java/com/sooum/api/card/service/FeedService.java
  data/core-data/src/main/java/com/sooum/data/tag/entity/Tag.java
Labels: 정우, refactor

#386 피드카드 상세조회 response에 isFeedCard 컬럼 추가
  boot/external-api/src/main/java/com/sooum/api/card/dto/FeedDetailCardDto.java
  boot/external-api/src/main/java/com/sooum/api/card/service/DetailFeedService.java
Labels: 정우, 지원, refactor

#393 신고당한 글 작성자 ip 저장 및 6개월 지난 신고 레코드 삭제 배치 코드 추가
  boot/batch/src/main/java/com/sooum/batch/report/batch/ReportDeleteBatchConfig.java
  data/core-data/src/main/java/com/sooum/data/report/entity/CommentReport.java
  data/core-data/src/main/java/com/sooum/data/report/entity/FeedReport.java
  data/core-data/src/main/java/com/sooum/data/report/repository/CommentReportRepository.java
  data/core-data/src/main/java/com/sooum/data/report/repository/FeedReportRepository.java
  data/core-data/src/main/java/com/sooum/data/report/service/CommentReportService.java
  data/core-data/src/main/java/com/sooum/data/report/service/FeedReportService.java
Labels: 정우, feature

#396 신고 시 신고 카드 컨탠츠 저장
  data/core-data/src/main/java/com/sooum/data/report/entity/CommentReport.java
  data/core-data/src/main/java/com/sooum/data/report/entity/FeedReport.java
  data/core-data/src/main/java/com/sooum/data/report/service/CommentReportService.java
  data/core-data/src/main/java/com/sooum/data/report/service/FeedReportService.java
Labels: 정우, feature

#400 Fix/nickname empty
  boot/external-api/src/main/java/com/sooum/api/member/service/ProfileService.java
  boot/external-api/src/main/java/com/sooum/api/notification/service/FCMMsgGenerator.java
Labels: fix, 호왕

#401 refactor: 닉네임 허용 유무 조회 API에서 파라미터를 String에서 dto로 변경
  boot/external-api/src/main/java/com/sooum/api/member/controller/ProfileController.java
  boot/external-api/src/main/java/com/sooum/api/member/dto/ProfileDto.java
  boot/external-api/src/main/java/com/sooum/api/member/service/ProfileService.java
Labels: 호왕, refactor

#404 fix: tag entity version 삭제
  data/core-data/src/main/java/com/sooum/data/tag/entity/Tag.java
  data/core-data/src/main/java/com/sooum/data/tag/repository/TagRepository.java
  data/core-data/src/main/java/com/sooum/data/tag/service/CommentTagService.java
  data/core-data/src/main/java/com/sooum/data/tag/service/FeedTagService.java
  data/core-data/src/main/java/com/sooum/data/tag/service/TagService.java
Labels: fix, 호왕, 정우, 지원

#406 Fix/transfer
  boot/external-api/src/main/java/com/sooum/api/member/controller/MemberSettingController.java
  boot/external-api/src/main/java/com/sooum/api/member/service/AccountTransferUseCase.java
  boot/external-api/src/main/java/com/sooum/api/member/service/MemberWithdrawalService.java
  boot/external-api/src/main/java/com/sooum/global/aop/aspect/RequesterInfoAspect.java
  data/core-data/src/main/java/com/sooum/data/member/entity/Member.java
  data/core-data/src/main/java/com/sooum/data/member/repository/MemberRepository.java
  data/core-data/src/main/java/com/sooum/data/member/service/MemberService.java
Labels: fix

#408 feat: 운영자 사칭 닉네임 금지
  boot/external-api/src/main/java/com/sooum/api/member/service/ProfileService.java
Labels: 호왕, feature

#410 refactor: 계정이관 시 기존 refreshToken blacklist에 등록
  boot/external-api/src/main/java/com/sooum/api/card/service/FeedService.java
  boot/external-api/src/main/java/com/sooum/api/member/controller/MemberAuthController.java
  boot/external-api/src/main/java/com/sooum/api/member/service/AccountTransferUseCase.java
  boot/external-api/src/main/java/com/sooum/api/member/service/BlackListUseCase.java
  boot/external-api/src/main/java/com/sooum/api/member/service/MemberInfoService.java
  boot/external-api/src/main/java/com/sooum/api/member/service/MemberWithdrawalService.java
  boot/external-api/src/main/java/com/sooum/global/auth/interceptor/JwtBlacklistInterceptor.java
  boot/external-api/src/main/java/com/sooum/global/auth/interceptor/exception/JwtBlacklistException.java
  boot/external-api/src/main/java/com/sooum/global/config/jwt/JwtAuthenticationFilter.java
  boot/external-api/src/main/java/com/sooum/global/config/jwt/RedisTokenPathPrefix.java
  boot/external-api/src/main/java/com/sooum/global/config/jwt/TokenProvider.java
  boot/external-api/src/main/java/com/sooum/global/config/jwt/exception/BlackListTokenException.java
  boot/external-api/src/main/java/com/sooum/global/config/jwt/exception/ExpiredRefreshTokenException.java
  boot/external-api/src/main/java/com/sooum/global/config/jwt/exception/InvalidTokenException.java
  boot/external-api/src/main/java/com/sooum/global/exceptionhandler/ValidExceptionHandler.java
  boot/external-api/src/main/resources/application.yml
  data/core-data/src/main/java/com/sooum/data/member/repository/RefreshTokenRepository.java
  data/core-data/src/main/java/com/sooum/data/member/service/RefreshTokenService.java
Labels: 호왕, refactor

#412 글 작성 시 밴 기간이 만료되었으면 role 변경 및 밴 기간 삭제
  boot/external-api/src/main/java/com/sooum/api/card/service/FeedService.java
  data/core-data/src/main/java/com/sooum/data/member/entity/Member.java
Labels: 정우, refactor

#414 차단 이력 조회 시 차단 기간이 풀렸으면 unban하는 로직 추가
  boot/external-api/src/main/java/com/sooum/api/member/service/MemberUseCase.java
Labels: 정우, feature

#418 fix: 계정이관 API에서 누락된 deviceType 데이터 받도록 수정
  boot/external-api/src/main/java/com/sooum/api/member/dto/AccountTransferDto.java
  boot/external-api/src/main/java/com/sooum/api/member/service/AccountTransferUseCase.java
  data/core-data/src/main/java/com/sooum/data/member/repository/MemberRepository.java
  data/core-data/src/main/java/com/sooum/data/member/service/MemberService.java
Labels: fix, 호왕

#425 Refactor/not delete report history
  boot/external-api/src/main/java/com/sooum/api/card/service/CardService.java
  boot/external-api/src/main/java/com/sooum/api/report/service/CommentReportUseCase.java
  boot/external-api/src/main/java/com/sooum/api/report/service/FeedReportUseCase.java
  boot/external-api/src/main/java/com/sooum/global/regex/BadWords.java
  data/core-data/src/main/java/com/sooum/data/member/entity/Member.java
Labels: 호왕, refactor

#427 feat: app version flag 조회 API 구현
  boot/external-api/src/main/java/com/sooum/api/appversion/controller/AppVersionController.java
  data/core-data/src/main/java/com/sooum/data/app/entity/AppVersionFlag.java
  data/core-data/src/main/java/com/sooum/data/app/repository/AppVersionFlagRepository.java
Labels: 호왕, feature

#432 refactor:CardUtils로 유틸성 메소드 추출
  boot/external-api/src/main/java/com/sooum/api/card/service/CommentInfoService.java
  boot/external-api/src/main/java/com/sooum/api/card/service/DistanceFeedService.java
  boot/external-api/src/main/java/com/sooum/api/card/service/FeedService.java
  boot/external-api/src/main/java/com/sooum/api/card/service/LatestFeedUseCase.java
  boot/external-api/src/main/java/com/sooum/api/card/service/PopularRetrieveService.java
  boot/external-api/src/main/java/com/sooum/api/card/service/TagFeedInfoService.java
  boot/external-api/src/main/java/com/sooum/global/util/CardUtils.java
Labels: 호왕, refactor

#433 dto 변경
  boot/external-api/src/main/java/com/sooum/api/card/dto/CardDto.java
  boot/external-api/src/main/java/com/sooum/api/card/dto/LatestFeedCardDto.java
  boot/external-api/src/main/java/com/sooum/api/card/dto/PopularCardRetrieve.java
  boot/external-api/src/main/java/com/sooum/api/card/service/FeedService.java
  boot/external-api/src/main/java/com/sooum/api/card/service/LatestFeedUseCase.java
  boot/external-api/src/main/java/com/sooum/api/card/service/PopularRetrieveService.java
Labels: 호왕, 정우, refactor
